### ISSUE TITLE
Document how to get help and contribute

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#101]
Currently we have no information in the docs how to get help or how to contribute:
http://astroplan.readthedocs.org/en/latest/

For help, i.e. user questions how to do XY, why AB doesn't work etc. I think pointing to the Astropy mailing list for now is fine. If there's a lot of questions, we can always set up our own mailing list.
Another good option might be stackoverflow with an astropy and / or astroplan tag.
@eteq – What do you think?

Concerning how to contribute, I think having a lot of text like http://photutils.readthedocs.org/en/latest/#contributing or https://sncosmo.readthedocs.org/en/v1.1.x/contributing.html isn't needed.
So I'd suggest just saying a few sentences like "same as Astropy, use Github" and point to http://astropy.readthedocs.org/en/latest/#contributing.
But a sentence or two like "this is a very young project, we very much welcome contributions of new features like planets, scheduling, GUI, ... just talk to us" are good to have, I think.

@jberlanga or @bmorris3 – Can you try to find a good place and wording for a short section on this in the docs?

**Comment by bmorris3** [comment]
@cdeil Would this be ok to stick in the FAQ section on a new page? I can't think of a more appropriate place.

**Comment by eteq** [comment]
Looks like this was done in #106 - I'll close this, but if we want more, this can always be re-opened.
