### ISSUE TITLE
Improve findability of example plots in the docs

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#102]
Currently via the [astroplan.plots API docs](http://astroplan.readthedocs.org/en/latest/api.html#id1), it's clear that we currently have three plots ... here's the API docs:
* [plot_airmass](http://astroplan.readthedocs.org/en/latest/api/astroplan.plots.plot_airmass.html)
* [plot_parallactic](http://astroplan.readthedocs.org/en/latest/api/astroplan.plots.plot_parallactic.html)
* [plot_sky](http://astroplan.readthedocs.org/en/latest/api/astroplan.plots.plot_sky.html)

The [Plotting with Astroplan](http://astroplan.readthedocs.org/en/latest/tutorials/plots.html) section does include examples for `plot_airmass` and `plot_sky`, but not for `plot_parallactic` (it mentions it, but no example shown). It took me a while to find an example of `plot_parallactic` ... it's in a [parallactic angle section in the summer triangle tutorial](http://astroplan.readthedocs.org/en/latest/tutorials/summer_triangle.html#parallactic-angle)

One thing that can be improved easily would be to link from the docstrings of the plot functions to the sections of the docs that contain examples of that plot.

Concerning the fact that no example parallactic plot is in the "Plotting with Astroplan" section, I'm not sure. Either add one (or move it from the summer triangle tutorial), or link to the existing example in the summer triangle tutorial.

**Comment by jberlanga** [comment]
@cdeil I didn't want to overwhelm the user with repetitive examples all on the same page (since `plot_airmass` and `plot_parallactic` work quite the same way), but of course you're right that it should be easier to find an example.  

I can fix this by linking to the existing plot or just assigning the different plot types to their own page and show the full range of plots possible for each type--any preferences?

**Comment by cdeil** [comment]
> I can fix this by linking to the existing plot or just assigning the different plot types to their own page and show the full range of plots possible for each type--any preferences?

Thanks!
I don't have a preference ... you decide!

The main point is that a new user should be able to find an example plot for each plot function quickly just starting from the top-level docs page by clicking or the search field.

**Comment by bmorris3** [comment]
I think it would make the most sense to have an example on the Plotting With Astroplan page, even if it's similar to the one on the Summer Triangle page. The Plotting With Astroplan page will be a reference that you can go to for all of the examples.

**Comment by bmorris3** [comment]
> One thing that can be improved easily would be to link from the docstrings of the plot functions to the sections of the docs that contain examples of that plot.

To double-check, would it be sufficient to include include links in the `plot_*` docstrings to the [Plotting with Astroplan](http://astroplan.readthedocs.org/en/latest/tutorials/plots.html) rtd tutorials?

**Comment by cdeil** [comment]
> To double-check, would it be sufficient to include include links in the plot_* docstrings to the Plotting with Astroplan rtd tutorials?

yes.
