### ISSUE TITLE
turn image comparison tests back on and get them working

### ISSUE THREAD

**Issue by eteq** [astropy/astroplan#107]
In #104 we turned the image comparison tests off because of some configuration issues, and didn't want that to interfere with 0.1.  They should be turned back on (and fixed!) in 0.2

cc @cdeil @bsipocz (also #81, although I think that's different from the original issue in #104 ?)

**Comment by wtgee** [comment]
Marking Issue as stale and closing. Looks like it was fixed in #115. Please re-open if still affected by this Issue.
