### ISSUE TITLE
pyephem dependency

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#111]
@eteq @bmorris3 – What's the plan / timeline for getting rid of the pyephem dependency in astroplan?

If it's likely ~ a year or longer, I'd suggest to change the conda package and put `pyephem` as a dependency, so that users automatically get the full functionality.

**Comment by bmorris3** [comment]
@eteq said (on Slack) he's working on an astropy fix that will make the
PyEphem workaround unnecessary. @eteq would it be feasible that the fix
might be ready by astroplan v0.2?

On Friday, September 11, 2015, Christoph Deil <notifications@github.com>
wrote:

> Assigned #111 <https://github.com/astropy/astroplan/issues/111> to
> @bmorris3 <https://github.com/bmorris3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astropy/astroplan/issues/111#event-406846066>.
>


-- 
Brett Morris
Graduate Student
Astronomy and Astrobiology
University of Washington
http://brettmorr.is

**Comment by bmorris3** [comment]
@eteq - we're nearing .Astronomy (two weeks way), any chance the `AltAz` fixes will be done by then so I can do a bunch of PRs to remove PyEphem from astroplan once and for all?

**Comment by bmorris3** [comment]
@eteq If I were to remove the PyEphem dependencies, update the moon methods, and change the requirements by the end of the week to astrpy v1.0.6, would you be able to review the PR? It shouldn't be a long PR and the tests don't have to change. 

I would also be able to implement `moon_rise_time` :exclamation:

**Comment by bmorris3** [comment]
Closed by #167.
