### ISSUE TITLE
UnitsError from test_parallactic_angle

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#126]
I'm getting this error with Astropy and astroplan master:
https://gist.github.com/cdeil/581945699d6c5bcdd354

I've seen these elsewhere, not sure if Numpy or Astropy changed.

@bmorris3 – Do you have time to fix this? (either pass the numpy assert numpy arrays, or use two quantities and pass them to the Astropy quantity assert function, but don't mix.) Or should I make a PR?

**Comment by bmorris3** [comment]
I also found that error and fixed it along with another fix in #125. Do you have time to review that PR?

**Comment by bmorris3** [comment]
I fixed this in #125, but forgot to tag this issue in that PR. Did that fix for the parallactic angle test work for you @cdeil?

**Comment by cdeil** [comment]
Fixed. Thanks.
