### ISSUE TITLE
IERS_A warning after downloading bulletin

### ISSUE THREAD

**Issue by tobyrsmith** [astropy/astroplan#132]
Talked with @bmorris3 about this issue, said I should post this.

```
In [1]: from astropy.time import Time

In [2]: import astropy.units as u

In [3]: from astroplan import Observer

In [4]: from astroplan import download_IERS_A

In [5]: download_IERS_A()
Downloading http://maia.usno.navy.mil/ser7/finals2000A.all
|==================================================================================| 3.0M/3.0M (100.00%)         6s

In [6]: now = Time("2016-10-28 00:00:00", format='iso')

In [7]: astrolab = Observer(longitude = -122.3115 *u.deg,
                    latitude = 47.65371*u.deg,
                    elevation = 63.4*u.m,
                    name = "Astrolab"
                    )

In [8]: sunset = astrolab.sun_set_time(now, which='nearest')
WARNING: Tried to get polar motions for times after IERS data is valid. Defaulting to polar motion from the 50-yr mean for those.
If you need enough precision such that this matters (~<10 arcsec), you can
download the latest IERS predictions by running:

    >>> from astropy.utils.data import download_file
    >>> from astropy.utils import iers
    >>> iers.IERS.iers_table = iers.IERS_A.open(download_file(iers.IERS_A_URL, cache=True))

 [astropy.coordinates.builtin_frames.utils]
WARNING: (some) times are outside of range covered by IERS table. Assuming UT1-UTC=0 for coordinate transformations.
If you need enough precision such that this matters (~<10 arcsec), you can
download the latest IERS predictions by running:

    >>> from astropy.utils.data import download_file
    >>> from astropy.utils import iers
    >>> iers.IERS.iers_table = iers.IERS_A.open(download_file(iers.IERS_A_URL, cache=True))

 [astropy.coordinates.builtin_frames.utils]
```

**Comment by bmorris3** [comment]
@tobyrsmith - could you respond also with your astroplan version (`astroplan.__version__`), astropy version (`astropy.__version__`) and Python version?

**Comment by tobyrsmith** [comment]
In [4]: astropy.__version__
Out[4]: '1.0.5'

In [5]: astroplan.__version__
Out[5]: '0.2.dev503'

Python 3.4.3

**Comment by bmorris3** [comment]
One more diagnostic thing to double check:

Does this return `True`?
```python
from astroplan.utils import IERS_A_in_cache  
IERS_A_in_cache()
```

@eteq Isn't this different from the intended behavior? I think we would prevent that astropy warning from being raised if astroplan updates astropy's IERS A table.

**Comment by tobyrsmith** [comment]
In [3]: from astroplan.utils import IERS_A_in_cache

In [4]: IERS_A_in_cache()
Out[4]: True

**Comment by eteq** [comment]
that's weird - indeed that warning shouldn't be coming up because you download the latest tables...

**Comment by eteq** [comment]
Oh, wait:
```
now = Time("2016-10-28 00:00:00", format='iso')
```
That's one year in the *future*, and I think the IERS A go 3 months or 6 months or something only...?

**Comment by bmorris3** [comment]
Despite the `now` assignment, that is the date that he intended. I think this may have exposed a corner case that we didn't check – if the dates requested are far enough in the future that they're off the most up-to-date IERS A table, you still get an astropy warning (or multiple). I'm assuming this is behavior we shouldn't override for any reason?

**Comment by bmorris3** [comment]
Pinging @eteq for clarification on the above question.
