### ISSUE TITLE
Update PyEphem times

### ISSUE THREAD

**Issue by bmorris3** [astropy/astroplan#133]
In astropy/astropy#4269 [it was mentioned](https://github.com/astropy/astropy/issues/4269#issuecomment-152920934) by @brandon-rhodes that we're using the wrong time for our PyEphem calculations. Wherever we call 
```
obs.date = time.datetime
```
it should in fact be:
```
obs.date = time.tt.datetime
````

**Comment by brandon-rhodes** [comment]
In the issue https://github.com/astropy/astropy/issues/4269 I did further investigation and, in fact, the PyEphem calling code was already doing the right thing! What instead needs to happen for an alt/az computation is that Skyfield needs Earth orientation data. We are thinking about adding an automated source of this data in the upcoming sprint, but for now the test code can do:
```
    delta_t = (53.7882 * 20 / 31) + (53.8367 * 11 / 31)
    jd = api.JulianDate(tt=time.tt.jd, delta_t=delta_t)
    moon_obs = loc.at(jd).observe(planets['moon'])
```

**Comment by bmorris3** [comment]
Thanks @brandon-rhodes! With that clarification I'll close the issue.
