### ISSUE TITLE
Astroplan citations

### ISSUE THREAD

**Issue by bmorris3** [astropy/astroplan#146]
This matter isn't pressing yet, but after #dotastro I've been thinking a lot about citation of code and I was hoping for some opinions on what we should promote as the proper citation for astroplan, if it ever comes up. Would making a quick Zenodo DOI for each release be good practice for now? 

And not to be considered until after the scheduling tools get written – what are your opinions on code papers? 

cc @eteq @adrn @cdeil

**Comment by cdeil** [comment]
> Would making a quick Zenodo DOI for each release be good practice for now?

I'm not sure if this is useful. It's a bit hard to imagine that users will start citing this, no? And having several DOIs, one for each release, will dilute citation count ... wouldn't it be better to have one or very few references that have some chance of getting a good citation count?

> what are your opinions on code papers?

I think that's a good idea to write a code paper at some point, but as you say, I think it makes sense to wait until `astroplan` accumulates more features.

If this takes long, a poster / conference proceeding might be nice in the meantime, if you're willing to make it and get it accepted somewhere (doesn't really matter, which conference).

Also, a logo and banner for astroplan would be nice ... it's not citations, but if some astronomer mentions astroplan in their presentation, and then someone else starts using it, that's a win.

Just as an example, [here](https://gammapy.readthedocs.org/en/latest/about.html#acknowledging-or-citing-gammapy) what we've done for Gammapy (i.e. a poster / conference proceeding and logo / banner).

And we should definitely apply for GSoC again with one or several project ideas ... I don't remember when this starts, maybe January or February to define / announce possible projects?

**Comment by cdeil** [comment]
@bmorris3 - I think my last comment was too negative on the Zenodo reference idea. I just meant that I have no idea if it's useful ... if you want to do it, :+1: .
