### ISSUE TITLE
Problem with airmass plots?

### ISSUE THREAD

**Issue by AlexaVillaume** [astropy/astroplan#149]
Hi all,

First, thanks for making what seems like a really great tool. I'm looking forward to incorporating it in my research. With that, I'm trying to make an airmass plot but there seems to be some issue. See attached image,

<img width="587" alt="screen shot 2016-03-04 at 5 21 10 pm" src="https://cloud.githubusercontent.com/assets/5116488/13544667/951eae1a-e22d-11e5-8ab7-741ad3b9a6fc.png">

I'm not sure why the lines continue vertically like they do and I'd prefer it if they didn't. Is there something wrong with how I'm setting up this plot that could be causing that?

```
keck = Observer.at_site('keck')
# Times need to be in UTC
start_time = Time('2016-04-04 05:00:00')
end_time = Time('2016-04-04 16:00:00')
delta_t = end_time - start_time
observe_time = start_time + delta_t*np.linspace(0, 1, 75)

coordinates = SkyCoord('03h40m11.904s', '-18d34m49.36s', frame='icrs')
obj1 = FixedTarget(coord=coordinates)

coordinates = SkyCoord('08h54m27.067s', '-03d04m01.56s', frame='icrs')
obj2 = FixedTarget(coord=coordinates)

plot_airmass(obj1, keck, observe_time)
plot_airmass(obj2, keck, observe_time)
plt.show()
~

**Comment by bsipocz** [comment]
@AlexaVillaume - Which version of ``astroplan`` do you use? 

This was an issue fixed after the 0.1 release was made. So if you're using 0.1 and prefer not to have the vertical lines (it's a bug, the vertical lines appear when the target is below the horizon), I would suggest to install the current development version.

**Comment by AlexaVillaume** [comment]
@bsipocz - Thank you for your reply. I was using version 0.1. I have now switched to the developer version and the vertical lines are gone.

**Comment by bmorris3** [comment]
Hi @AlexaVillaume! I also fixed the incomplete x-axis label in that update. 

Please let us know if we can improve anywhere else! In the mean time, I think this issue has been addressed.
