### ISSUE TITLE
Nearest midnight incorrect

### ISSUE THREAD

**Issue by barentsen** [astropy/astroplan#155]
The output of `Observer.midnight()` is incorrect when the input time falls within ~30 sec of the nearest midnight, for example:

``` Python
In [1]: from astroplan import Observer
In [2]: from astropy.time import Time
In [3]: observer = Observer.at_site('aao')
In [4]: observer.midnight(Time('2016-03-01 14:19:52'), which='nearest').iso
Out[4]: '2016-03-02 14:19:24.551'
```

Note that the output in the above example is 24 hours later than the input time, which is incorrect.

This is related to #145, but probably warrants a separate unit test.

**Comment by bmorris3** [comment]
When I try this, I get: 
```
In [3]: from astroplan import Observer

In [4]: from astropy.time import Time

In [5]: observer = Observer.at_site('aao')

In [6]: observer.midnight(Time('2016-03-01 14:19:52'), which='nearest').iso
Out[6]: '2016-03-01 14:13:54.948'
```

Do you still get the above result if you try it again? This is interesting.
