### ISSUE TITLE
SNR over the night

### ISSUE THREAD

**Issue by yoachim** [astropy/astroplan#156]
While astronomers traditionally look at airmass plots, what we really should be considering is the signal-to-noise ratio that can be achieved at different times.  For example, I can't compute off the top of my head if it's better to observe an object at low airmass with the moon up, or high airmass with the moon down.

I might take a crack at making a simple sky background model and basic assumptions about extinction and seeing variations to see how it looks.  Probably don't want a full exposure time calculator, but it might be nice to plot the relative SNR that can be achieved through the night.

**Comment by bsipocz** [comment]
:+1:

**Comment by bmorris3** [comment]
Please do @yoachim! Having a starting point in the form of a PR will make it clearer how easy/difficult it would be to make a fully generalized SNR tool for everyone to use.

**Comment by ejeschke** [comment]
I think this would be very nice.  I wonder how well it could deal with the complexity of various instruments.

Our [HSC exposure time calculator](https://hscq.naoj.hawaii.edu/cgi-bin/HSC_ETC/hsc_etc.cgi) is written in python and I know the authors well (they are just down the hall).  If you are interested we could probably get the code pretty easily just as an example of a current working (optical) instrument ETC to help inform the kind of end use cases.

**Comment by bmorris3** [comment]
It would be great if you could ask them about their openness to sharing it. What are the chances that they'd release the code on GitHub, with an appropriate license such that we can fork it and adapt it?

I think that approaching this problem with @yoachim's or HSC's code as starting points could make this problem approachable for astroplan.

**Comment by bsipocz** [comment]
This sounds super exciting and useful. If there'll be any need for an extra
pair of hands to help adopting it into the astroplan api feel free to ping
me.

**Comment by yoachim** [comment]
@ejeschke The code behind that moon phase plot would be super useful--especially if they have it for more optical-IR filters.  Once we have even a crude sky background from the moon, the rest is pretty easy.

**Comment by bmorris3** [comment]
Hey @yoachim – did you ever get a chance to hack together a sky background model that might be applicable to astroplan?

**Comment by yoachim** [comment]
Not really.

**Comment by bmorris3** [comment]
Then I'm going to close this issue and thank you for the idea. Thanks!
