### ISSUE TITLE
Feature astroplan.herokuapp.com

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#157]
I think we should feature astroplan.herokuapp.com from the astroplan docs and encourage contributions there. (Well, once https://github.com/barentsen/astroplan-webapp/issues/3 is resolved, looks like it's broken at the moment.)

It's a nice example to play around with a bit, and people can use it as a starting point if they want to develop their own web app for astroplanning (or any astropy / matplotlib web GUI really).

@bmorris3 - Any thoughts where a short description and link to this app fits in the docs?

cc @barentsen

**Comment by bmorris3** [comment]
I think it be appropriate to stick a little note on the front page (i.e. [this one])[http://astroplan.readthedocs.io/en/latest/index.html], do you @cdeil?

**Comment by cdeil** [comment]
> I think it be appropriate to stick a little note on the front page (i.e. this one), do you @cdeil?

👍

**Comment by pllim** [comment]
Heroku sux now.
