### ISSUE TITLE
'Column' object has no attribute 'mask'

### ISSUE THREAD

**Issue by zemogle** [astropy/astroplan#160]
I'm getting this weird problem. I've uninstalled and re-pip installed. I've also got the latest development version.

I'm running `python==2.7`, `astropy==1.1.2` and `numpy==1.11.0` on a Raspberry Pi (Raspbian).

```
----> 1 from astroplan import download_IERS_A

/home/pi/astroplan/astroplan/__init__.py in <module>()
     29     from .constraints import *
     30 
---> 31     get_IERS_A_or_workaround()

/home/pi/astroplan/astroplan/utils.py in get_IERS_A_or_workaround()
     51     """
     52     if IERS_A_in_cache():
---> 53         iers.IERS.iers_table = _get_IERS_A_table()
     54     else:
     55         Time._get_delta_ut1_utc = _low_precision_utc_to_ut1

/home/pi/astroplan/astroplan/utils.py in _get_IERS_A_table(warn_update)
     86     if IERS_A_in_cache():
     87         path = download_file(iers.IERS_A_URL, cache=True, show_progress=True)
---> 88         table = iers.IERS_A.open(path)
     89         # Use polar motion flag to identify last observation before predictions
     90         index_of_last_observation = ''.join(table['PolPMFlag_A']).index('IP')

/home/pi/env/allsky/local/lib/python2.7/site-packages/astropy/utils/iers/iers.pyc in open(cls, file, cache, **kwargs)
    143                 else:
    144                     kwargs.update(file=file)
--> 145             cls.iers_table = cls.read(**kwargs)
    146         return cls.iers_table
    147 

/home/pi/env/allsky/local/lib/python2.7/site-packages/astropy/utils/iers/iers.pyc in read(cls, file, readme)
    372         # presumably to be filled later.  Exclude those a priori -- there
    373         # should at least be a predicted UT1-UTC and PM!
--> 374         return cls(iers_a[~iers_a['UT1_UTC_A'].mask &
    375                           ~iers_a['PolPMFlag_A'].mask])
    376 

AttributeError: 'Column' object has no attribute 'mask'
```

**Comment by bmorris3** [comment]
Maybe @eteq or @mhvk would know? Looks like the problem is occurring in astropy.

**Comment by zemogle** [comment]
I was thinking that too. Maybe clearing the cached file would be enough. I suspect the download only partially happened and something got itself in a pickle.

**Comment by bmorris3** [comment]
If the IERS table was incompletely downloaded/corrupt, you can delete it by clearing the astropy cache. 

If there is _nothing_ in the astropy cache that you care about, I think you can clear it by deleting the files in `~/.astropy/cache/download` (at least that's what I've done when I have similar problems).

**Comment by zemogle** [comment]
So, I manually ran all the code in `_get_IERS_A_table` line by line and setting `cache=False` (i.e. force the file to download again) works. Clearly the cached version of the IERS A table was mess, and clearing out all the cache fixed that nicely.

Thanks!

Ps. I love astroplan - I'm ditching pyephem in favour of it :grinning:

**Comment by bmorris3** [comment]
Excellent, I'm glad the fix wasn't too painful.

I'm glad you love it! Would you mind sharing what you're doing with it on raspberry pi? I'm excited to see the code proliferating.

**Comment by zemogle** [comment]
Sure! I've installed an [AllSky camera in a Dark Sky Reserve](http://www.zemogle.uk/allsky/). Its being controlled by the Raspberry Pi using only Python (with the communication going through [INDi](http://indilib.org/)). `astropy` has made my life so much simpler.

The biggest problem is making the USB cables waterproofed (I live in Wales) :umbrella:

**Comment by bmorris3** [comment]
Awesome. Are you using `astroplan` to compute sunrise/set times?

**Comment by zemogle** [comment]
Yes indeed! Its not in the live version yet but hopefully it will be soon.

On 7 April 2016 at 19:55, Brett M. Morris <notifications@github.com> wrote:

> Awesome. Are you using astroplan to compute sunrise/set times?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/astropy/astroplan/issues/160#issuecomment-207049132>
>



-- 
Edward Gomez - Education Director
Las Cumbres Observatory Global Telescope Network, UK
+44 (0) 29 2087 5121
