### ISSUE TITLE
Add example of added features to plotting tutorials

### ISSUE THREAD

**Issue by eteq** [astropy/astroplan#163]
I just noticed that the tutorial at http://astroplan.readthedocs.io/en/latest/tutorials/plots.html does not show any of the features from #150... I presume that's not intentional?  It probably should because those are nice features!

**Comment by bmorris3** [comment]
Somewhat unrelated – do you know why the [finder chart](http://astroplan.readthedocs.io/en/latest/tutorials/plots.html#finder-chart-image) doesn't get displayed on the RTD page?
