### ISSUE TITLE
MoonIlluminationConstraint returns One-Dimensional Array

### ISSUE THREAD

**Issue by jkunimune15** [astropy/astroplan#183]
It seems that because moon illumination is independent of target, the compute_constraint method of MoonIlluminationConstraint returns a one-dimensional array, as opposed to a two dimensional array as the other Constraints return. This causes a problem in SequentialScheduler's _make_schedule method, where the mismatching shapes cause np.prod() to return an array instead of a scalar, which throws an exception.

**Comment by bmorris3** [comment]
@jkunimune15 @StuartLittlefair Should this have been closed by #165?

**Comment by StuartLittlefair** [comment]
Yes I think it should
