### ISSUE TITLE
SequentialScheduler throws error calling TransitionBlock.target

### ISSUE THREAD

**Issue by jkunimune15** [astropy/astroplan#184]
In `SequentialScheduler._make_schedule()`, the `Transitioner.__call__()` method is invoked on the last element in `new_blocks`, which requires that the last element is an ObservingBlock. However, when nothing is observable, `new_blocks` is appended with a TransitionBlock, which causes an eventual exception when `Transitioner.__call__()` tries to reference `new_blocks[-1].target`.

**Comment by bmorris3** [comment]
Hi @jkunimune15. Thanks for your comments so far today. 

The scheduling code is in active development right now, and you should assume that none of it works. We appreciate the issue posts, but @kvyh is working full time right now to turn this sketch of a module into something usable, so bear with us as we flesh it out.

**Comment by kvyh** [comment]
There are a few issues with the current code in both of the schedulers that will hopefully be fixed with PR #182. Further work on the foundations of the schedulers is also ongoing.

**Comment by wtgee** [comment]
Marking Issue as stale and closing. Please re-open if still affected by this Issue.
