### ISSUE TITLE
Python3.5.2 causes setup.py to throw an error

### ISSUE THREAD

**Issue by kvyh** [astropy/astroplan#186]
With python3.5.2, there is apparently no ConfigParser attribute to distutils.config. This is causes the setup.py to error (at line 25 of setup.py), and causes checks using python3.5 to fail.

**Comment by kvyh** [comment]
I'll see if I can find a fix for it, but help understanding how the backwards/forwards compatibility works would be appreciated.

**Comment by bsipocz** [comment]
FYI the fixes are already included in #177.

**Comment by bsipocz** [comment]
This can be closed now.
