### ISSUE TITLE
A suggestion to allow vectorised constraints

### ISSUE THREAD

**Issue by StuartLittlefair** [astropy/astroplan#189]
On attempting to deploy astroplan for our own scheduling problem we are finding that it is much slower than our old solution. Each scheduling step with ~20 targets takes ~20 secs. 

There are some optimisations being discussed in #179 which may give a factor 2 speedup, but this is not sufficient. 

There are further optimisations possible by converting looking at converting `lists` of `FixedTargets` to non-scalar `SkyCoord`  object to speedup alt-az calculations, but these won't apply in our use case.

What I am proposing is to adapt the `Constraints` classes, so that a `Constraint` can take a vector of parameters. As a concrete example, one can currently create an `AirmasConstraint` like this:

``` python
ac_scalar = AirmassConstraint(max=3)
```

However, in our use case we have many targets, which may all have `AirmassConstraint`s, but with different limits. At the moment these all have their own independent `AirmassConstraint`s, so the compute time scales with the number of targets.

Instead I propose we allow

``` python
ac_vector = AirmassConstraint(max=[2, 1.5, 3])
```

A call to `ac_vector.compute_constraint(times, observer, targets)` in which the shape of `targets` cannot be broadcast to the `min` and `max` attributes of `ac_vector` would raise a `ValueError`. Otherwise, broadcasting would occur.

This would be **much** quicker for an end user who wants to apply one type of constraint to many targets, but with different limits for each target. I imagine this is a common use case. 

`Schedulers` could also implement logic that would group (for example) all the `AirmassConstraints` in a list of `ObservingBlocks` into a single, vectorised `AirmassConstraint` and see the same speedup benefits.

Comments @bmorris3, @eteq, @kvyh?

**Comment by kvyh** [comment]
I think that it makes a lot of sense to allow that. Finding out which `ObservingBlocks` have a particular `Constraint` would be the only part that a `scheduler` would need to do, and that shouldn't be too hard.

**Comment by kvyh** [comment]
Actually, after trying to write it up, it appears to be much more complicated to implement, unless the constraint applies to every block. The current way that schedulers are called uses individual and global constraints, the individual constraints are stored within the blocks that are fed into the scheduler, and the global constraints are fed directly into the scheduler. It would be easy to have the scorer handle a vectorized global constraint, but if you want to vectorize constraints that are stored in the blocks it is difficult to reclaim the Parameters to make them into a vector. It should be straightforward to make a method inside `Constraint` that is able to vectorize a list of itself though, which would solve the issue of reclaiming parameters.

**Comment by bmorris3** [comment]
@StuartLittlefair I think this sounds potentially valuable. Writing schedulers is already pretty difficult, so it will take some time to migrate these features into the preliminary schedulers that are being developed now. 

Like you mentioned, this will be most useful for the case when an observer wants to do: 
```python
target1, target2, target3 = ...
constraints = AirmassConstraint(max=[3, 2, 1.5])
```
The docs will have to be very clear about `list` inputs do. You could imagine a user thinking that you could call `AirmassConstraint(max=[3, 2, 1])` on a single target to get three different airmass constraint evaluations on that one target.

**Comment by bmorris3** [comment]
I believe this issue can be closed when #424 is merged, right @StuartLittlefair?

**Comment by StuartLittlefair** [comment]
I believe so, although we should probably open a separate, but related, issue, since at the moment I think you can actually create a ```Constraint``` with a vectorised list of constraints quite happily, but I'm not sure it broadcasts sensibly when used...

**Comment by wtgee** [comment]
Marking Issue as stale and closing. Please re-open if still affected by this Issue.
