### ISSUE TITLE
Add unit tests for Observer

### ISSUE THREAD

**Issue by adrn** [astropy/astroplan#19]
Right now, there are many functional tests to compare with output from PyEphem. We need unit tests!

**Comment by bmorris3** [comment]
Can you clarify the difference? What is missing?

**Comment by adrn** [comment]
Sure. 

A "unit test" tests a specific function or method, or a specific part of a function / method, with many different inputs / checks for failure modes / etc. These meant primarily to check that the code executes with valid input, returns valid output with valid input, fails as expected, etc. For example, you could write some very simple tests for `_generate_24hr_grid` that check that (for all possible valid inputs) you get back a length `N` `Time` object. Other good ones are to check for failure modes: What happens if you pass in a `float` for `N` instead of an `int`? Are there any cases for which it should fail? If so, [you can check and require that it throws an error](https://pytest.org/latest/assert.html#assertions-about-expected-exceptions). For this function it's not critical that the tests are too extensive because it is an internal function, but same principles.

A "functional test" (sometimes called an integration test, but sometimes they are considered different...) tests more of the user-facing code and are what you mainly have implemented now -- e.g., checking calculations that may involve smaller pieces of code against output from PyEphem.

Many people have written many words about the differences / utilities of each (google 'unit test vs functional test'). Here's a blog post that (I haven't read) but has some examples: http://jeffknupp.com/blog/2013/12/09/improve-your-python-understanding-unit-testing/

**Comment by cdeil** [comment]
@adrn – agreed that unit tests are important, but ...

IMO a few functional tests are more important, so I like that @bmorris3 started with those.
There can be millions of lines of code and unit tests, and still the software isn't functional, i.e. can't do the major use cases.
Personally I'd prefer @bmorris3 works on features, e.g. making the code work with arrays of targets and adding a functional test for that.
One can easily spend many days or weeks thinking of and implementing unit tests for everything and especially invalid input handling / response.

So maybe we can agree that @bmorris3 should implement more unit tests (or unit tests at all ... I haven't been really looking too closely) in the coming weeks, but try to avoid this becoming too big of a time sink, i.e. also spend time on more features and high-level tests?

**Comment by adrn** [comment]
@cdeil it's always about finding the balance of functional and unit tests. I should've made it more clear: this issue isn't even necessarily for @bmorris3, but is to remind us that there is definitely room to add some unit tests (by someone...at some point).

**Comment by adrn** [comment]
However, @bmorris3 is responsible for #18 !

**Comment by adrn** [comment]
(I assigned the units to hopefully make this more clear)

**Comment by cdeil** [comment]
@adrn – OK, then we're on the same page.

@bmorris3 – If you have any questions about what / how to test, please ask!
Developing good tests, i.e. tests that cover a lot of ground, but are easy to read and write, is hard.
Probably browsing the tests in `astropy.coordinates` for a while is a good way to learn.

**Comment by cdeil** [comment]
Current coverage report for Observer:
https://coveralls.io/builds/3413013/source?filename=astroplan%2Fcore.py#L108
(overall OK, but there's a few methods / branches of if statements that are untested)

@bmorris3 – Can you make a PR to address this issue and #18 ? Or do you want to move those to the 0.2 milestone?

**Comment by bmorris3** [comment]
@cdeil If time allows, I'd like to address #18 in time for 0.1, but the updates that I want to make for #18 depend on #69 getting merged.

I'd be happy to let #19 (this issue) slide until 0.2, and I'd like to remind @adrn of his apt prompt: 

>  that there is definitely room to add some unit tests (by someone...at some point). 

After all @adrn, it's presently some point, and he's currently someone. :wink:
