### ISSUE TITLE
observability_table not sortable

### ISSUE THREAD

**Issue by wtgee** [astropy/astroplan#197]
The returned observability_table is not sortable because of the `Observer` object stored in the table's metadata. How compelling is the need to have that metadata? I would much rather be able to easily sort my table via `fraction` (the table also currently has unfriendly column names).

**Comment by bmorris3** [comment]
Could you make an example showing the problem?

**Comment by wtgee** [comment]
I think this is on my end, sorry for noise. I inherit from `Observer` and it appears something in my class is not doing the deepcopy correctly.
