### ISSUE TITLE
Scheduler: from_timespan in base class

### ISSUE THREAD

**Issue by wtgee** [astropy/astroplan#206]
Do the `from_timespan` classes plan to diverge in the `SequentialScheduler` and the `PriorityScheduler` (and future `Scheduler`s)?  Currently they are the same and I was going to move them to the base `Scheduler` class for some cleanup but wanted to check first.

https://github.com/astropy/astroplan/blob/master/astroplan/scheduling.py#L438
https://github.com/astropy/astroplan/blob/master/astroplan/scheduling.py#L558

**Comment by bmorris3** [comment]
I can't think of a reason yet why they couldn't be moved up. @kvyh ?

**Comment by kvyh** [comment]
That should be a standard `@classmethod` for a `scheduler`, yup.

**Comment by wtgee** [comment]
Similarly, both `SequentialScheduler` and `PriorityScheduler` are not calling the base class `__init__` method but instead are repeating the same code. If there's no specific reason for this I can get it cleaned up so they are actually inheriting those base properties.

**Comment by bmorris3** [comment]
I think that sounds fine. 

These two schedulers were each implemented independently, so I think this kind of coordination just hadn't been considered until you brought it up.

**Comment by wtgee** [comment]
Closed by #207
