### ISSUE TITLE
Scheduler callable interface question

### ISSUE THREAD

**Issue by wtgee** [astropy/astroplan#209]
I don't understand the reasoning behind making a `Scheduler` class callable instead of just making the `make_schedule` method public. It doesn't seem very intuitive to me.

Also, as it exists now there is a bug somewhere in `_make_schedule` such that it cannot actually be called twice in a row. So, for example in the #208 that @kvyh just posted (linked below) there is a separation between the creation of a `Scheduler` and the calling of it, but you can't actually ever call it twice. (That's probably a separate Issue)

https://github.com/kvyh/astroplan/blob/7cf328a4ebadcc6592cc4c68d63df7e0cf6e88fa/docs/tutorials/scheduling.rst#scheduling

**Comment by wtgee** [comment]
Actually, you can't call it twice because it is reusing the `self.schedule` in a weird way. If you recreate `self.schedule` at the top of `_make_callable` (instead of in `init`) then it works twice in a row. However, there is some weird caching going on. The first call takes ~45s on my laptop whereas the second call is 600ms. (`%timeit` reports the discrepancy)

**Comment by bmorris3** [comment]
@wtgee You might not know that @kvyh is a Google Summer of Code intern working with fleshing out the first scheduler implementations in astroplan. It will take some time before any of these scheduler features are fully supported, and we appreciate your patience (and help!) in the mean time.

The API choice of making `Scheduler`s callable is so that you can call a scheduler with the same properties on different sets of observing blocks. The current version is not prepared to do that properly yet.

**Comment by kvyh** [comment]
When I was writing the code, I wasn't considering using the same scheduler twice. Moving the creation of the `schedule` to the `_make_schedule` should allow it to be called multiple times, I will fix that as soon as I have time. Some constraints do cache values, which has the potential for speeding it up the second time.

**Comment by wtgee** [comment]
Yeah, no worries and I didn't mean to put any pressure on or call anything into question, I was just wondering if there was a design decision around  the callable. I don't quite understand the response but I have not good reason to change it either. :)

And I know that it's not being optimized for speed or anything at this point. I realize that just getting it working is a ton of effort and appreciate the work @kvyh is doing. If I'm complicating things by jumping into the code too early let me know!

**Comment by wtgee** [comment]
@kvyh I guess my thought is you would have one type of `Scheduler` that you would use to make multiple `Schedule`s by passing different `ObservingBlock`s. We have long running processes that would need to generate a new `Schedule` every night, ideally from the same `Scheduler` that was created when the process was created. That could be changed depending on the intended use however.

**Comment by kvyh** [comment]
The utility of being able to call the same `Scheduler` multiple times is great, I'll be doing a PR soon with a few changes talked about in #217. That should make it possible to use the same `Scheduler` multiple times, as long as you have a new `Schedule` to input.
