### ISSUE TITLE
0.1 release

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#21]
At the start we said that we'll release 0.1 at GSoC mid-term and 0.2 at the end of GSoC.

It's clear that releasing now doesn't make sense, because basic functionality is work in progress and there's no end-user high-level docs yet. So I've just now moved the 0.1 release milestone on Github to August 10, but even that is flexible, we'll just release when we think 0.1 makes sense.

IMO it will be when the basic toolbox is assembled, so that users can try it out and file feature requests / issues, and it becomes possible to parallelise the work more, i.e. should there be other people that want to hack on this package to add features, it's easily possible without too much coordination.

We can use this issue to discuss when we think 0.1 should be released and, if there are any issues how to make a release or with the release, we can discuss solutions here.
(PS: I'd be happy if someone else does releases / announcements / maintenance for this package for the coming months, only if no-one else wants to do it, I can do it.)

**Comment by cdeil** [comment]
As discussed in today's hangout, @bmorris3 will do the 0.1 release.

**Comment by cdeil** [comment]
The 0.1 release is done ... closing this issue:

@bmorris3 and @jberlanga  - Thank you, great work!

* Conda package: https://github.com/astropy/conda-builder-affiliated/pull/51
* PyPI: https://pypi.python.org/pypi/astroplan
* Announcement: https://groups.google.com/forum/#!topic/astropy-dev/POuBYg503kk

There's a few more things to do ...

@jberlanga - I'd suggest in addition posting the announcement here:
http://mail.scipy.org/mailman/listinfo/astropy

@bmorris3 - Can you update the astroplan docs a bit to mention that astroplan is not an Astropy-affiliated package and that conda install exists?

There's an issue in the astropython.org page ... astroplan isn't properly listed yet:
https://github.com/astropy/astropython.org/issues/19
Probably we just have to wait a bit until they straighten that out.

**Comment by cdeil** [comment]
FYI: the reason astroplan currently isn't found via search on PyPI:
https://pypi.python.org/pypi?%3Aaction=search&term=astroplan&submit=search

seems to be a PyPI bug that is being worked on:
https://bitbucket.org/pypa/pypi/issues/326/some-packages-not-showing-up-when

**Comment by jberlanga** [comment]
@cdeil - At some point (maybe @eteq or @adrn ?) said they preferred to post the announcement for 0.1 on astropy-dev only.  I missed your request yesterday to put it on the astropy mailing list as well, or I would have mentioned it then.

**Comment by adrn** [comment]
@jberlanga Not sure who it was but I do think it would be good to post to the astropy list as well!

**Comment by jberlanga** [comment]
@cdeil @adrn -- Done!
