### ISSUE TITLE
Readthedocs builds are broken

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#214]
The readthedocs build for astroplan has been broken for ~ a month:

https://readthedocs.org/projects/astroplan/builds/
https://readthedocs.org/projects/astroplan/builds/4264804/

Looks like it's just the PDF build and the HTML build is OK?

I don't have time to investigate.
@bsipocz or @bmorris3 - maybe you do?

**Comment by bmorris3** [comment]
I don't understand what the failure is. I hate to put another thing on @bsipocz's long list – but maybe she's our best hope.

**Comment by bsipocz** [comment]
Honestly I have no idea what's the problem. However photutils seems to have the same or very similar issue for the pdf builds. https://github.com/astropy/photutils/issues/393

**Comment by larrybradley** [comment]
I just wanted to add that this issue is unrelated to https://github.com/astropy/photutils/issues/393.  They are independent bugs in the docs.
