### ISSUE TITLE
Calling Schedulers with Schedules

### ISSUE THREAD

**Issue by kvyh** [astropy/astroplan#217]
The current  code creates a `Schedule` during the initialization. I will be removing the creation of a `Schedule` from the `__init__` and adding a `Schedule` as a required argument for the `__call__` (which will then require a list of `ObservingBlocks` and a `Schedule`). After the change it will be possible to input a `Schedule` that has already be added to into the `Schedulers`. 

Using a partially filled `Schedule` is **not** advised since neither `Scheduler` can accommodate it at this time. Adding this functionality is a future goal.

**Comment by bmorris3** [comment]
I think this was addressed by the above mentioned PRs.
