### ISSUE TITLE
Add more docs on FixedTarget initialization

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroplan#226]
Based on recent e-mails on the dev list, it seems to be useful to repeat a bit of the ``SkyCoord`` documentation, or at least point to it here:

https://astroplan.readthedocs.io/en/latest/tutorials/summer_triangle.html#defining-objects

E.g. how one uses object names rather than coordinates to initialize the ``Observer``.

**Comment by bmorris3** [comment]
I'm not sure I understand – are people curious about what observatories are available? Do you think we should have a clearer link in those docs to the [`EarthLocation.of_site`](http://docs.astropy.org/en/stable/api/astropy.coordinates.EarthLocation.html#astropy.coordinates.EarthLocation.of_site) docs?

**Comment by bsipocz** [comment]
You clearly don't read astropy-dev ;)
I meant that the objects can be given by their simbad compatible name. This is not really an astroplan issue, and maybe a link to the SkyCoord docs is enough. Anyway I guess it's not trivial to see for someone who has no experience with astropy.coordinates. A quote from the e-mail:

> I had a quicklook at it. From what I understood astroobs looks easier/faster to use; part is because it queries SIMBAD - e.g. no need to input the target coordinates (see the README examples).

**Comment by bmorris3** [comment]
I see – you including a link to defining the `Observer` object in your first post, but I think you're talking about docs for the `FixedTarget.from_name` constructor, which wraps around `SkyCoord.from_name`. 

Now I understand and agree – the first example should use the `from_name` method. I'm on it!

**Comment by bmorris3** [comment]
> You clearly don't read astropy-dev ;)

@bsipocz And for the record – I get daily digests of astropy-dev, so I am behind you by a few hours, but I am reading!

**Comment by bsipocz** [comment]
👍

Also it seems that I was in a bad shape right after lunch when writing this issue. Had I started looking at the very beginning of the docs, I would have found a good example for Altair. So now I'm not sure what else we can do to make it easier to spot.

**Comment by bsipocz** [comment]
My link above is not the right one, what about updating the example right at the beginning, https://astroplan.readthedocs.io/en/latest/getting_started.html#general-guidelines? It tricked me twice that 'Altair' is going to Skycoord/Simbad, but it's not.
