### ISSUE TITLE
Docs Improvements

### ISSUE THREAD

**Issue by bmorris3** [astropy/astroplan#237]
I have a few TODOs for @kvyh that I'm going to sketch here with some screenshots, based on the just merged #218. 

I merged the docs as they were because that's the most convenient way to gather group input on the [built sphinx docs](https://astroplan.readthedocs.io/en/latest/tutorials/scheduling.html), cc @eteq and @ejeschke.

Below are my comments for @kvyh: 

---

<img width="708" alt="screen shot 2016-08-17 at 8 34 56 pm" src="https://cloud.githubusercontent.com/assets/3497584/17761223/2f8b71b8-64ba-11e6-81da-a52c469b42d9.png">

These lines are really long. They'd be more readable and fit better if the `ObservingBlock.from_exposures` part was called on its own line, then passed into `blocks.append` on a separate line. 

Also, would you change `rot` to a full word, or leave a comment which describes what it is?

---

<img width="706" alt="screen shot 2016-08-17 at 8 37 03 pm" src="https://cloud.githubusercontent.com/assets/3497584/17761254/62fb72fa-64ba-11e6-8f9a-d8969ff9e504.png">

This table doesn't show up very well here. Is it possible to format it differently so that it shows up? Or maybe we shouldn't show it?

**Comment by kvyh** [comment]
On https://astroplan.readthedocs.io/en/latest/tutorials/scheduling.html, the table shows up with the right side cut off, but you can scroll to see it. I definitely agree on the line length for the block definition though, maybe: ```
b = Obser.......
blocks.append(b)```

**Comment by bmorris3** [comment]
Maybe the table shows up differently for me because I'm using Safari?

And yes, that's the pattern that I'm thinking for the OB call + append.

**Comment by bsipocz** [comment]
The table looks fine in firefox for me. However the plots are not, the bottom half of the xlabels are missing.

**Comment by kvyh** [comment]
#238 fixes the x-labels.

**Comment by bmorris3** [comment]
@kvyh  While we're cleaning up the two lines like:
```python
ObservingBlock.from_exposures(Deneb, priority, 60*u.second, 16, rot,
                                                      configuration = {'filter': bandpass},
                                                      constraints = [first_half_night]))
```
would you create variables with descriptive names above the `for` loop that store the values `60*u.second, 16` which are passed to the `ObservingBlock.from_exposures` constructor? It's not clear what those numbers represent, but if you first set the variable `exposure_duration = 60*u.sec` and then use `exposure_duration`, it will be easy to see what the arguments of the `ObservingBlock.from_exposures` constructor are.

***

Also, could you make the variable names for Deneb and M13 lowercase ([PEP8](https://www.python.org/dev/peps/pep-0008/#global-variable-names))?

**Comment by kvyh** [comment]
I've shortened the line lengths and made the variables more descriptive in the most recent commits to #238.
