### ISSUE TITLE
Add MoonTargetSeparationRange constraint

### ISSUE THREAD

**Issue by ejeschke** [astropy/astroplan#24]
This is a constraint on the distance from target(s) to the moon.  It would specify a minimum and maximum angular separation.  Either minimum or maximum can be None, in which case there is no constraint in that direction.  (Typically we might assume that only a minimum separation would be specified, but I know of engineering items that would require a maximum as well).

This is dependent on having a reliable way to get the moon position and calculate the angular separation.

**Comment by bmorris3** [comment]
`MoonSeparationConstraint` was added in #61.
