### ISSUE TITLE
Sunrise/sunset Times Not Accurate

### ISSUE THREAD

**Issue by joshwalawender** [astropy/astroplan#242]
I'm getting inaccurate sunrise and sunset times.  The odd bit is that the calculation for 12 and 18 degree twilights is spot on.  Here's an example where I calculate tonight's times for Keck (in local times):

```
from astropy import units as u
from astropy.time import Time, TimezoneInfo
from astroplan import Observer

obs = Observer.at_site('Keck')
HST = TimezoneInfo(utc_offset=-10*u.hour, tzname='HST')
date = '2016-08-22'
time = Time('{} 23:00:00'.format(date))

sunset = obs.sun_set_time(time, which='next', horizon=0*u.deg)
print('Sunset:          {}'.format(sunset.to_datetime(timezone=HST)))
sunset = obs.sun_set_time(time, which='next', horizon=-12*u.deg)
print('12 deg Twilight: {}'.format(sunset.to_datetime(timezone=HST)))
sunset = obs.sun_set_time(time, which='next', horizon=-18*u.deg)
print('18 deg Twilight: {}'.format(sunset.to_datetime(timezone=HST)))
sunrise = obs.sun_rise_time(time, which='next', horizon=-18*u.deg)
print('18 deg Twilight: {}'.format(sunrise.to_datetime(timezone=HST)))
sunrise = obs.sun_rise_time(time, which='next', horizon=-12*u.deg)
print('12 deg Twilight: {}'.format(sunrise.to_datetime(timezone=HST)))
sunrise = obs.sun_rise_time(time, which='next', horizon=0*u.deg)
print('Sunrise:         {}'.format(sunrise.to_datetime(timezone=HST)))
```

The output is:

```
Sunset:          2016-08-22 18:41:00.637777-10:00
12 deg Twilight: 2016-08-22 19:33:40.070690-10:00
18 deg Twilight: 2016-08-22 20:00:30.753806-10:00
18 deg Twilight: 2016-08-23 04:48:34.130495-10:00
12 deg Twilight: 2016-08-23 05:15:24.788828-10:00
Sunrise:         2016-08-23 06:08:04.168392-10:00
```

When I compare against [Brian Casey's Online Calculator](http://www.briancasey.org/artifacts/astro/almanac.cgi?command=display&year=2016&month=08&day=22&observatory=m&obslong=&obslat=&actual=&effective=&sitename=&zone=&zonename=&zoneabbrev=&daylight=1) and against the [Mauna Kea Weather Center ](http://mkwc.ifa.hawaii.edu/forecast/mko/index.cgi) (scroll to bottom of page to see the times), my astroplan calculations for sunset and sunrise are off by 13 minutes, but the twilight times are within 1 minute.

**Comment by bmorris3** [comment]
This is due to atmospheric refraction. Astropy accounts for atmospheric refraction for targets `altitude >= 0`, but refraction can't be computed for `altitude < 0`, which would explain why your tests agree below the horizon, and disagree above the horizon.

Here's an example that demonstrates the difference. Let's compute the position of the sun at the time of sunset computed by astroplan: 
```python
from astroplan import Observer

import astropy.units as u
from astropy.time import Time
from astropy.coordinates import get_sun, AltAz, EarthLocation

location = EarthLocation.of_site('keck')
keck = Observer.at_site('keck')
sunset = keck.sun_set_time(Time('2016-08-23'), which='next')
sun = get_sun(sunset)


# Set up an alt/az reference frame _with_ an atmosphere:
aa_frame_1bar = AltAz(location= keck.location, obstime=sunset, pressure=1*u.bar)

# Set up an alt/az reference frame _without_ an atmosphere
aa_frame_no_atm = AltAz(location= keck.location, obstime=sunset, pressure=0*u.bar)

# Compute the altitude of the sun in each reference frame:
altitude_no_atm = sun.transform_to(aa_frame_no_atm).alt
altitude_1bar_atm = sun.transform_to(aa_frame_1bar).alt

# Compute the difference in altitudes in each reference frame, in arcminutes:
altitude_difference = (altitude_no_atm - altitude_1bar_atm).to(u.arcmin)
print(altitude_difference)
```
This returns `-11.569arcmin`, which roughly accounts for the 13+/-1 minute discrepancy you're seeing.

So in fact astroplan is not inaccurate, it is computing a different quantity than your point of comparison.

**Comment by joshwalawender** [comment]
@bmorris3 Thanks for the info.  I have a couple of questions.  First, I would think that -11.569 arcmin should only delay sunset by of order a minute (at ~15 arcminutes per minute sidereal rate), not 13 minutes.

Second, how would I calculate the time of apparent sunset?

thanks!
Josh

**Comment by bmorris3** [comment]
@joshwalawender That sounds reasonable. It's difficult to compare against a black box and understand all of the differences, but the fact that we agree closely below the horizon suggests that astropy treats targets above the horizon differently than the calculator you're comparing against. 

Perhaps @eteq can comment on what other second-order corrections are applied to the AltAz coordinate calculations, which will differ from simpler calculators?

> Second, how would I calculate the time of apparent sunset?

`Observer.sun_set_time` returns the time when the center of the solar disk is on the horizon, given the refraction, aberration, and other corrections applied -- is this what you mean by apparent sunset? Note that in practice, air pressure, temperature, humidity and other quantities can change the observed time of apparent sunset.

**Comment by joshwalawender** [comment]
Thanks @bmorris!  I think I understand now.  The last bit of my confusion was accounting for the "true horizon" due to the curvature of the Earth.  That was where my discrepancy came from.  When I add in the factor of the true horizon, my `astroplan` calculations match the time of perceived sunset (checked on web cams tonight) to within less than a minute.

The time difference with no atmosphere vs. a 620mbar atmosphere (at elevation of Mauna Kea) is about 30 seconds.

I'm going to close this now, but in case anyone is interested:

```
from astropy import units as u
from astropy.time import Time, TimezoneInfo
from astroplan import Observer
from astropy.coordinates import get_sun, AltAz, EarthLocation
import numpy as np

## Calculate Elevation of True Horizon
## Formulas from https://en.wikipedia.org/wiki/Horizon
h = 4.2*u.km
R = (1.0*u.earthRad).to(u.km)
d = np.sqrt(h*(2*R+h))
phi = (np.arccos((d/R).value)*u.radian).to(u.deg)
hzel = phi - 90*u.deg
print('Mauna Kea Sunset is at elevation of {}'.format(hzel))

keck = Observer.at_site('Keck')
HST = TimezoneInfo(utc_offset=-10*u.hour, tzname='HST')
date = '2016-08-25'
time = Time('{} 23:00:00'.format(date))

sunset = keck.sun_set_time(time, which='next', horizon=0*u.deg)
print('Sunset:            {}'.format(sunset.to_datetime(timezone=HST)))
sunset = keck.sun_set_time(time, which='next', horizon=hzel)
print('Mauna Kea Sunset:  {}'.format(sunset.to_datetime(timezone=HST)))

# By default, this sun will be initialized in GCRS coordinates
sun = get_sun(sunset)
# Set up an alt/az reference frame _with_ an atmosphere:
aa_frame_atm = AltAz(location=keck.location, obstime=sunset, pressure=0.620*u.bar)
# Set up an alt/az reference frame _without_ an atmosphere
aa_frame_no_atm = AltAz(location=keck.location, obstime=sunset, pressure=0*u.bar)
# Compute the altitude of the sun in each reference frame:
altitude_no_atm = sun.transform_to(aa_frame_no_atm).alt
altitude_atm = sun.transform_to(aa_frame_atm).alt
print(altitude_no_atm)
print(altitude_atm)

sunset = keck.sun_set_time(time, which='next', horizon=-12*u.deg)
print('12 deg Twilight:   {}'.format(sunset.to_datetime(timezone=HST)))
sunset = keck.sun_set_time(time, which='next', horizon=-18*u.deg)
print('18 deg Twilight:   {}'.format(sunset.to_datetime(timezone=HST)))
sunrise = keck.sun_rise_time(time, which='next', horizon=-18*u.deg)
print('18 deg Twilight:   {}'.format(sunrise.to_datetime(timezone=HST)))
sunrise = keck.sun_rise_time(time, which='next', horizon=-12*u.deg)
print('12 deg Twilight:   {}'.format(sunrise.to_datetime(timezone=HST)))
sunrise = keck.sun_rise_time(time, which='next', horizon=hzel)
print('Mauna Kea Sunrise: {}'.format(sunrise.to_datetime(timezone=HST)))
sunrise = keck.sun_rise_time(time, which='next', horizon=0*u.deg)
print('Sunrise:           {}'.format(sunrise.to_datetime(timezone=HST)))
```

Results in:

```
Mauna Kea Sunset is at elevation of -2.0800907212114623 deg
Sunset:            2016-08-25 18:38:38.241043-10:00
Mauna Kea Sunset:  2016-08-25 18:47:39.116887-10:00
-2d04m48.9216s
-1d57m59.4462s
12 deg Twilight:   2016-08-25 19:31:02.668566-10:00
18 deg Twilight:   2016-08-25 19:57:42.667814-10:00
18 deg Twilight:   2016-08-26 04:49:42.686269-10:00
12 deg Twilight:   2016-08-26 05:16:23.109695-10:00
Mauna Kea Sunrise: 2016-08-26 05:59:46.406136-10:00
Sunrise:           2016-08-26 06:08:47.378015-10:00
```

**Comment by bmorris3** [comment]
Excellent! That observational test is the best test I've heard of yet.
