### ISSUE TITLE
astroplan 0.1.1?

### ISSUE THREAD

**Issue by mwcraig** [astropy/astroplan#245]
The documentation indicate (by way of changelog) that there was an astroplan 0.1.1 release, but it doesn't show up on pypi or github. A new release would be very helpful 😄  because of the `ConfigParser` issue on python 3.5 (this has been fixed in this repo, but there is not a release with it yet).

**Comment by bmorris3** [comment]
Hi @mwcraig – there was a plan for an immediate 0.1.1 release that got shelved temporarily (for my wedding). I intend to get out an v0.2 release this week with @kvyh's Summer of Code work and the `ConfigParser` fix, among other things.

Thanks for checking in!

**Comment by mwcraig** [comment]
@bmorris3 congrats! I worked around it for now. Please remember to open a PR at https://github.com/astropy/conda-channel-astropy to update the conda package when you do the release.

Really nice job on this package, by the way. I just started digging in to it a couple weeks ago and had no clue how convenient it is!

**Comment by bmorris3** [comment]
The new version (v0.2) is uploaded to pypi, and PR astropy/conda-channel-astropy#74 has been initiated. Thanks for the reminder @mwcraig!

And thanks for the kind words! Don't be quite about feedback :)
