### ISSUE TITLE
plot_finder_image. Unexpected keyword argument: 'radius'

### ISSUE THREAD

**Issue by DanielAndreasen** [astropy/astroplan#247]
This function does not work properly. I try to follow the example in the tutorial and get the following error

    from astroplan import FixedTarget
    from astroplan.plots import plot_finder_image
    import matplotlib.pyplot as plt

    messier1 = FixedTarget.from_name("M1")
    ax, hdu = plot_finder_image(messier1)
    plt.tight_layout()
    plt.show()

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-96-7d43b094b5fd> in <module>()
          4 
          5 messier1 = FixedTarget.from_name("M1")
    ----> 6 ax, hdu = plot_finder_image(messier1)
          7 plt.tight_layout()
          8 plt.show()

    /home/daniel/Software/anaconda3/lib/python2.7/site-packages/astropy/utils/decorators.py in plot_finder_image(target, survey, fov_radius, log, ax, grid, reticle, style_kwargs, reticle_style_kwargs)
        634             name = func.__name__
        635 
    --> 636         func = make_function_with_signature(func, name=name, **wrapped_args)
        637         func = functools.update_wrapper(func, wrapped, assigned=assigned,
        638                                         updated=updated)
    
    /home/daniel/Software/anaconda3/lib/python2.7/site-packages/astropy/units/decorators.pyc in wrapper(*func_args, **func_kwargs)
        128             # Call the original function with any equivalencies in force.
        129             with add_enabled_equivalencies(self.equivalencies):
    --> 130                 return wrapped_function(*func_args, **func_kwargs)
        131 
        132         return wrapper
    
    /home/daniel/Software/anaconda3/lib/python2.7/site-packages/astroplan/plots/finder.pyc in plot_finder_image(target, survey, fov_radius, log, ax, grid, reticle, style_kwargs, reticle_style_kwargs)
         86 
         87     hdu = SkyView.get_images(position=position, coordinates=coordinates,
    ---> 88                              survey=survey, radius=fov_radius, grid=grid)[0][0]
         89     wcs = WCS(hdu.header)
         90 
    
    TypeError: get_images() got an unexpected keyword argument 'radius'

Other than that, eveyrthing so far seems to work well. Thank you so much for this package! :+1:

**Comment by kvyh** [comment]
The code runs well on my machine. 'SkyView.get_images()` is a part of astroquery. Is it possible you have an old version of astroquery?

**Comment by DanielAndreasen** [comment]
Was exactly the reason. Had version 0.2.4, after upgrading with `pip install astroquery -U` to version 0.3.2 everything works. Thanks
