### ISSUE TITLE
PyQT4

### ISSUE THREAD

**Issue by bmorris3** [astropy/astroplan#248]
PyQT5 is causing CI failures, so based on the suggestion in astropy/astropy#5340, we've fixed the version to `pyqt=4`. If/when a solution is found, repair astroplan also!

**Comment by bmorris3** [comment]
Hey @bsipocz - though your PR passed the tests, the main astroplan build is now failing. Do you know if the change in your PR could have caused [the IERS](https://travis-ci.org/astropy/astroplan/jobs/164971800#L736) warnings to be raised again?

**Comment by bsipocz** [comment]
I don't think it could cause it directly, but those warnings were never really dealt with properly (as far as I remember) so I assume anything would retrigger them sooner or later.

**Comment by kvyh** [comment]
The warning that you linked showed up before. It should pass if [the exception](https://travis-ci.org/astropy/astroplan/jobs/164971800#L746) is fixed.

**Comment by bsipocz** [comment]
@bmorris3 - I suggest to close this issue and open another one for the IERS issue as it's totally unrelated. Maybe there is already a discussion on that somewhere?
