### ISSUE TITLE
DocTestFailure in Observer.__repr__

### ISSUE THREAD

**Issue by ViviCoder** [astropy/astroplan#251]
When I run tests, I get a failure with the following message:

```
________________ [doctest] astroplan.observer.Observer.__repr__ ________________
188         """
189         String representation of the `~astroplan.Observer` object.
190 
191         Examples
192         --------
193 
194         >>> from astroplan import Observer
195         >>> keck = Observer.at_site("Keck", timezone="US/Hawaii")
196         >>> print(keck)                                    # doctest: +FLOAT_CMP
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,3 @@
     <Observer: name='Keck',
         location (lon, lat, el)=(-155.478333333 deg, 19.8283333333 deg, 4160.0 m),
    -    timezone=<DstTzInfo 'US/Hawaii' LMT-1 day, 13:29:00 STD>>
    +    timezone=<DstTzInfo 'US/Hawaii' HST-1 day, 13:30:00 STD>>

astroplan/astroplan/observer.py:196: DocTestFailure
```

It looks like a version problem of some package, but I can't find which. Any idea?

**Comment by bmorris3** [comment]
Interesting – what version of `pytz` are you using? You can find out by doing: 

```python
In [1]: import pytz

In [2]: pytz.__version__
Out[2]: '2016.6.1'
```

**Comment by bmorris3** [comment]
@bsipocz – do you know if the `# doctest: +FLOAT_CMP` call in this docstring should prevent the failure that we're seeing here?

**Comment by ViviCoder** [comment]
@bmorris3 -- I'm using version 2015.7. It does not seem to be the problem here, since I tried on another more recent distribution but with the same pytz version, and it worked.

**Comment by bmorris3** [comment]
What do you mean by 
> another more recent distribution

What version of `pytest` are you using?

**Comment by ViviCoder** [comment]
By more recent distribution, I mean Debian sid.
I'm using pytest 2.8.5, whereas sid uses 3.0.2.

**Comment by bsipocz** [comment]
> @bsipocz – do you know if the # doctest: +FLOAT_CMP call in this docstring should prevent the failure that we're seeing here?

No, I don't think so,  and I also would be surprised if it gave a pass for the the string difference in the timezone.

**Comment by bmorris3** [comment]
I'm not sure where this difference is arising from. Which version of Python are you running?

**Comment by ViviCoder** [comment]
I'm using Python 3.4.2, and 3.5.1 is used in sid.

**Comment by bmorris3** [comment]
@ViviCoder - is this affecting any other tests, or only the doctests?

**Comment by ViviCoder** [comment]
@bmorris3 Sorry, I made a mistake. I'm using Python 2.7.9, whereas 2.7.11 is used in sid.
All other tests work fine.

**Comment by bmorris3** [comment]
I think our Python tests use the most recent version of Python (2.7.12) and they're passing - would you be able to update your Python distribution?

**Comment by ViviCoder** [comment]
Not easily. I know it worked on sid with Python 2.7.11, but a lot of other packages are also more recent, so it's difficult to find out the origin of the issue.
Anyway, it is not a big deal.
