### ISSUE TITLE
Incorrect shading in plot_airmass

### ISSUE THREAD

**Issue by mwcraig** [astropy/astroplan#255]
Under some (arguably unusual) circumstances, `plot_airmass` produces incorrect shading, with daylight shaded light grey.

An example to reproduce the error is below; it produces this airmass plot:

![image](https://cloud.githubusercontent.com/assets/1147167/19422726/7b8a1742-93de-11e6-8c34-6584149579f4.png)

Local midnight is 6UTC,

Code to reproduce:

```python
# Load a couple of things needed from astroplan
from astroplan import Observer, FixedTarget
from astroplan.plots import plot_airmass, plot_finder_image

# And load Time from astropy
from astropy.time import Time
feder = Observer(latitude="46.86678d", longitude="263.54672d")
my_object = FixedTarget.from_name('M108')

obs_time = Time("2016-12-02 00:59:00", scale='utc')
plot_airmass(my_object, feder, obs_time, brightness_shading=True, altitude_yaxis=True)
```

**Comment by wtgee** [comment]
I'll take a look at this as I had adjusted the shading code last. I ran into this same issue a while back and think it's a pretty easy fix. I'll get back to you shortly. Thanks for reporting @mwcraig

**Comment by mwcraig** [comment]
Thanks for the quick response -- @janeglanzer was the one who noticed the problem while working on an assignment this week.
