### ISSUE TITLE
Finder chart?

### ISSUE THREAD

**Issue by profxj** [astropy/astroplan#262]
I have a pretty simple module that will generate one or more finder charts (PDF)
given an input list of coords (in one of several formats).   Requires astropy,
astroquery, PIL, and cStringIO  [I might be able to use alternates for the latter two].

Would this repository be a good place for such code?  If so, I'll fork and generate
a PR before long.  

Here is the main module, for what it is worth:

https://github.com/xastropy/xastropy/blob/master/xastropy/obs/finder.py

**Comment by bmorris3** [comment]
Hi @profxj! Would you be able to show us a code example that shows how to generate a finder chart, and what the outputs look like? We have a basic finder chart function [`astroplan.plots.plot_finder_image`](https://astroplan.readthedocs.io/en/latest/api/astroplan.plots.plot_finder_image.html#astroplan.plots.plot_finder_image) within astroplan based on astroquery also ([see this tutorial for a demo](https://astroplan.readthedocs.io/en/latest/tutorials/plots.html#finder-image)), but there's plenty of room for improvement there.

**Comment by bmorris3** [comment]
Hi @profxj – still interested to see if you'd like to make a PR, otherwise I'll close this issue. Thanks!

**Comment by wtgee** [comment]
Marking Issue as stale and closing. @profxj feel free to open back up with PR if applicable.
