### ISSUE TITLE
Problems with IERS_A download

### ISSUE THREAD

**Issue by PhysicsFTW** [astropy/astroplan#267]
The URL seems to be down and the work around doesn't work. This is preventing all target look-ups from working. Any suggestions for fix/ different work around?

@wtgee

**Comment by wtgee** [comment]
Just to add to @PhysicsFTW, we are trying to use astroplan in a few places and on the machines that we have ever used the module the `get_IERA_A_or_workaround` does seem to work, but on fresh installs that method doesn't do much. This is causing some travis-cl timeouts for us as well in panoptes/POCS.

Thanks!

**Comment by bmorris3** [comment]
Hi all! We need to find a more permanent solution than this, but I discussed this problem and a workaround in astropy/astropy#5059, [see here](https://github.com/astropy/astropy/issues/5059). This mirror URL seems to be working: 
```
http://toshi.nofs.navy.mil/ser7/finals2000A.all
```

**Comment by PhysicsFTW** [comment]
Thanks @bmorris3. if we manually download this file, where is the correct place to download it to?

**Comment by PhysicsFTW** [comment]
We used 
```
from astropy.utils import iers

iers.IERS_A_URL = 'http://toshi.nofs.navy.mil/ser7/finals2000A.all'

download_IERS_A()
```

Thanks for the help!
