### ISSUE TITLE
attempting to determine rise/set times with single objects leads to error about truth value of array

### ISSUE THREAD

**Issue by aakepley** [astropy/astroplan#268]
I'm trying to figure out the rise/set times of some objects at the GBT. Following the tutorial online, I've got the following code. However, it fails with "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()" None of the inputs look to be arrays, so how is it triggering this warning?

I did a clean anaconda install and installed astroplan via conda (conda install -c astropy astroplan).

I'm running
```
astroplan.__version__
u'0.2'
astropy.__version__
u'1.2.1'
```
and Python 2.7.12 |Anaconda 4.2.0 (x86_64), which is what the clean anaconda install provided.

```
from astroplan import Observer
import astropy.units as u

from astropy.coordinates import SkyCoord
from astroplan import FixedTarget
from astropy.time import Time

gbt = Observer(longitude=(-79,50,23.406)*u.deg, latitude=(38,25,59.236)*u.deg, elevation=807.43*u.m,name='gbt',timezone='US/Eastern')

galaxy = FixedTarget.from_name('NGC1068')

time = Time('2017-02-01 17:00:00')

gbt.target_is_up(time, galaxy)

>>> execfile('rise_set.py')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rise_set.py", line 14, in <module>
    gbt.target_is_up(time, galaxy)
  File "/Users/amanda/anaconda2/lib/python2.7/site-packages/astropy/utils/decorators.py", line 636, in target_is_up
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "/Users/amanda/anaconda2/lib/python2.7/site-packages/astropy/units/decorators.py", line 130, in wrapper
    return wrapped_function(*func_args, **func_kwargs)
  File "/Users/amanda/anaconda2/lib/python2.7/site-packages/astroplan/observer.py", line 1553, in target_is_up
    observable = bool(altaz.alt > horizon)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by bmorris3** [comment]
Hi! The problem here is with the way you're defining the observer latitude and longitude. 
```python
In [1]: import astropy.units as u
In [2]: (-79,50,23.406)*u.deg
Out[2]: <Quantity [-79.   , 50.   , 23.406] deg>
```
This latitude and longitude have shape `(3,)` because it looks like you're writing the degrees, minutes and seconds components separately and defining them all has having units degrees, but you just want one latitude and one longitude. To correct this, you could do this: 

```python
from astroplan import Observer
import astropy.units as u

from astropy.coordinates import SkyCoord, EarthLocation
from astroplan import FixedTarget
from astropy.time import Time

# Using lat/lon in the format you have them
gbt = Observer(location=EarthLocation.from_geodetic(lon='-79d50m23.406s', lat='38d25m59.236s'), elevation=807.43*u.m,name='gbt',timezone='US/Eastern')

# Or looking more like your original command with corrected lat/lon in degrees
gbt = Observer(longitude=-79.839835*u.deg, latitude=38.433121111111106*u.deg, elevation=807.43*u.m, name='gbt', timezone='US/Eastern')

galaxy = FixedTarget.from_name('NGC1068')
time = Time('2017-02-01 17:00:00')
gbt.target_is_up(time, galaxy)
```
The above returns `False`.

**Comment by aakepley** [comment]
Thanks! That works now. BTW, the reason I did the tuple was that the Observer documentation said that latitude and longitude could be any valid astropy.coordinates.Latitude/Longitude object those objects can be fed tuples as I was reading the documentation.

**Comment by bmorris3** [comment]
Ah, I see, sorry that's tricky. Your original lat/lon may be valid inputs to the `Latitude` and `Longitude` objects, but they're not valid `Latitude` and `Longitude` objects themselves.
