### ISSUE TITLE
Add MoonIlluminationRange constraint

### ISSUE THREAD

**Issue by ejeschke** [astropy/astroplan#27]
This is a constraint on the illumination of the moon. It would specify a minimum and maximum illumination as a percentage. Either minimum or maximum can be None, in which case there is no constraint in that direction.  This allows target selection when a user is requesting dark or grey nights.

It would be nice if this could support the case where the moon is below the horizon.  In other words, we need to consider not only the orbital phase, but the degree to which the moon is visible.  If the user specifies a 0.1 (10%) maximum illumination and the moon phase is 50%, but the moon is not yet risen, the constraint is satisfied.

**Comment by bmorris3** [comment]
`MoonIlluminationConstraint` was added in #61.
