### ISSUE TITLE
Many failures with astropy 1.3

### ISSUE THREAD

**Issue by wtgee** [astropy/astroplan#278]
There are quite a number of failures with astropy 1.3. In particular the new vector-based `SkyCoord` and `Time` cause a number of failures but in addition most of the test suite fails.

I'll start working on a PR later today but wanted to get the issue created.

**Comment by wtgee** [comment]
Sorry, sort of a duplicate of #263. Since it's now an astropy release rather than dev it seems like a bit of a higher priority.

**Comment by bsipocz** [comment]
@wtgee - I have a number of open PRs that address most of those failures, and basically there are only two issues left.
One is with ``remote-data`` that seems to be broken at the moment (running without remote-data, we get quite a few failures), and the other is a broadcasting issue.

**Comment by wtgee** [comment]
Closing this in favor of #263
