### ISSUE TITLE
SequentialSchedular not getting executed

### ISSUE THREAD

**Issue by lordaniket06** [astropy/astroplan#291]
As instructed in the Astroplan Doc [Scheduling an Observing Run](http://astroplan.readthedocs.io/en/stable/tutorials/scheduling.html) , after defining the Observer location ,constraints etc. The Sequential Scheduler does give any output, instead this error.

`Traceback (most recent call last):
  File "<pyshell#45>", line 1, in <module>
    seq_scheduler(blocks, sequential_schedule)
  File "/usr/local/lib/python3.5/dist-packages/astroplan/scheduling.py", line 463, in __call__
    schedule = self._make_schedule(copied_blocks)
  File "/usr/local/lib/python3.5/dist-packages/astroplan/scheduling.py", line 584, in _make_schedule
    if block_constraint_results[bestblock_idx] == 0.:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Comment by bmorris3** [comment]
Would you include the code you wrote that produces this error?

**Comment by lordaniket06** [comment]
Here is the code I used-
``` python
from astroplan import Observer
from astroplan import FixedTarget
from astropy.time import Time
from astroplan.constraints import AtNightConstraint, AirmassConstraint
from astroplan import ObservingBlock
from astroplan.constraints import TimeConstraint
from astropy import units as u
from astroplan.scheduling import Transitioner
from astroplan.scheduling import SequentialScheduler
from astroplan.scheduling import Schedule

apo = Observer.at_site('apo')

deneb = FixedTarget.from_name('Deneb')
m13 = FixedTarget.from_name('M13')

noon_before = Time('2016-07-06 19:00')
noon_after = Time('2016-07-07 19:00')

global_constraints = [AirmassConstraint(max = 3, boolean_constraint = False), AtNightConstraint.twilight_civil()]

read_out = 20 * u.second

deneb_exp = 60*u.second
m13_exp = 100*u.second
n = 16
blocks = []

half_night_start = Time('2016-07-07 02:00')
half_night_end = Time('2016-07-07 08:00')
first_half_night = TimeConstraint(half_night_start, half_night_end)

for priority, bandpass in enumerate(['B', 'G', 'R']):
    
    b = ObservingBlock.from_exposures(deneb, priority, deneb_exp, n, read_out, configuration = {'filter': bandpass}, constraints = [first_half_night])
    blocks.append(b)

    b = ObservingBlock.from_exposures(m13, priority, m13_exp, n, read_out, configuration = {'filter': bandpass}, constraints = [first_half_night])
    blocks.append(b)

slew_rate = .8*u.deg/u.second
transitioner = Transitioner(slew_rate, {'filter':{('B','G'): 10*u.second, ('G','R'): 10*u.second, 'default': 30*u.second}})

seq_scheduler = SequentialScheduler(constraints = global_constraints, observer = apo, transitioner = transitioner)

sequential_schedule = Schedule(noon_before, noon_after)

seq_scheduler(blocks, sequential_schedule)
```

**Comment by lordaniket06** [comment]
It is same as that given in the Astroplan Doc. The only difference is I compiled the whole code before executing it. Although with the traditional IDLE3 it gives the same error. So I doubt that is much of a difference.
  However when I use `PriorityScheduler` instead of `SequentialScheduler` , the code got stuck without giving any reasonable output/error . I suspect maybe its a run-time error.

**Comment by bsipocz** [comment]
@lordaniket06 - What do you exactly mean by compiling this code before executing?

**Comment by bsipocz** [comment]
@lordaniket06 - Could you please live us the version of astroplan and astropy you use? Your example code works without raising an exception for me when using the latest dev version.

```
import astroplan
print(astroplan.__version__)
import astropy
print(astropy.__version__)
```

**Comment by lordaniket06** [comment]
@bsipocz The version that I'm currently using is 0.2 for astroplan and 1.3 for astropy . If these are not the latest versions please tell me how to upgrade it. As I installed astroplan/astropy using
`pip3 install astropy`
`pip3 install astroplan`

**Comment by bsipocz** [comment]
OK, so that's a know issue then. Version 0.2 is not compatible with astropy 1.3. So if you're planning to use it for work, I suggest to downgrade astropy to be 1.2 or install the development version of astroplan.

On the other hand, if you are planning to apply for GSoC, you should definitely install the dev version os astroplan, and I also strongly suggest to use the dev astropy version, too.

**Comment by bsipocz** [comment]
@bmorris3 @eteq - I wonder whether we could have a 0.2.1 version with all the fixes that got merged into master recently?

**Comment by lordaniket06** [comment]
@bsipocz I tried to install the dev version of Astropy as you said but later when I try to import it I get an error saying, There is no module named Astropy. I used the following commands
```shell
git clone git://github.com/astropy/astropy.git
python setup.py build
python setup.py install
```
Also I did not get any error while installing

**Comment by bsipocz** [comment]
Please see the dev guide about setting up the environment here: http://docs.astropy.org/en/latest/development/workflow/development_workflow.html
