### ISSUE TITLE
Unable to get Observer.sun_set_time() to work with astroplan-0.2, astropy-1.3

### ISSUE THREAD

**Issue by astrochun** [astropy/astroplan#292]
I'm using astroplan v0.2 with astropy v1.3 and I seem to be getting a new error that did not exist before (v0.1 with astropy v1.1.2).  Unsure of this is connected with the astropy/astroplan incompatibility as I upgraded to v1.3 earlier this year from v.1.1.2.

Traceback (most recent call last):
  File "mmt_queue_2017a.py", line 24, in <module>
    CL_tab0 = mmt_ephemeris.table_sun_rise_set(dates, start_date, end_date)
  File "mmt_ephemeris.py", line 202, in table_sun_rise_set
    verbose=verbose)
  File "mmt_ephemeris.py", line 140, in get_sun_rise_set
    print '## blah3 : ', obs.sun_set_time(time0, which='nearest') #.to_datetime()
  File "/Users/cly/apps/anaconda/lib/python2.7/site-packages/astropy/utils/decorators.py", line 860, in sun_set_time
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "/Users/cly/apps/anaconda/lib/python2.7/site-packages/astropy/units/decorators.py", line 130, in wrapper
    return wrapped_function(*func_args, **func_kwargs)
  File "/Users/cly/apps/anaconda/lib/python2.7/site-packages/astroplan/observer.py", line 1143, in sun_set_time
    return self.target_set_time(time, get_sun(time), which, horizon)
  File "/Users/cly/apps/anaconda/lib/python2.7/site-packages/astropy/utils/decorators.py", line 860, in target_set_time
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "/Users/cly/apps/anaconda/lib/python2.7/site-packages/astropy/units/decorators.py", line 130, in wrapper
    return wrapped_function(*func_args, **func_kwargs)
  File "/Users/cly/apps/anaconda/lib/python2.7/site-packages/astroplan/observer.py", line 960, in target_set_time
    horizon=horizon))
  File "/Users/cly/apps/anaconda/lib/python2.7/site-packages/astroplan/observer.py", line 830, in _determine_which_event
    next_event = function(*args('next'))
  File "/Users/cly/apps/anaconda/lib/python2.7/site-packages/astroplan/observer.py", line 714, in _calc_riseset
    altaz = self.altaz(times, target)
  File "/Users/cly/apps/anaconda/lib/python2.7/site-packages/astroplan/observer.py", line 464, in altaz
    list(map(get_coord, target)))
TypeError: argument 2 to map() must support iteration

**Comment by bmorris3** [comment]
Would you please share the source code that produces this error?

**Comment by astrochun** [comment]
Below is the code.  github does not seem to allow to attach a .py file.

The table_sun_rise_set() function calls astroplan. Given a list of dates formatted as 'YYYY-MM-DD', it returns a table containing sunrise/set and twilight begin/end.

This code works with v0.1 of astroplan and astropy v1.1.2 (I did not try it w/ astropy v1.3).


`"""
mmt_ephemeris
====

Computes ephemeris info at the location of MMT Observatory
"""

import sys, os

from chun_codes import systime

from os.path import exists
import commands

import numpy as np

#import matplotlib.pyplot as plt

from astropy.table import Table

from astropy.coordinates import EarthLocation
from astropy.time import Time, TimezoneInfo # Mod on 11/03/2017
from astroplan import Observer, FixedTarget
import astropy.units as u

import datetime
import pytz

# Initialize Observer object at the location of MMT
MMT      = EarthLocation.from_geodetic('259d06m56s', '31d41m20s', 2600)
obs      = Observer(location=MMT, timezone='US/Mountain')
local_tz = pytz.timezone('US/Mountain')

# + on 01/03/2017
utc_mst = TimezoneInfo(utc_offset=-7*u.hour)
mst_utc = TimezoneInfo(utc_offset=+7*u.hour)

def local_to_utc(time):
    '''
    Convert local time at MMTO to UTC time

    Parameters
    ----------
    time : ISO 8601 formatted date and time 'YYYY-MM-DD'
	  
    Returns
    -------
    utc_time : ISO 8601 formatted date and time for UTC

    Notes
    -----
    Created by Chun Ly, 11 August 2016
    '''

    #utc_time = time.to_datetime(timezone=mst_utc)
    utc_time = time.replace(tzinfo=local_tz).astimezone(tz=pytz.utc)
    return utc_time
#enddef

def utc_to_local(time):
    '''
    Convert UTC time to local time at MMTO

    Parameters
    ----------
    time : ISO 8601 formatted date and time 'YYYY-MM-DD'
	  
    Returns
    -------
    local_time : ISO 8601 formatted date and time for UTC

    Notes
    -----
    Created by Chun Ly, 11 August 2016
    '''

    local_time = time.replace(tzinfo=pytz.utc).astimezone(tz=local_tz)
    return local_time
#enddef

def str_hhmm(value):
    '''
    Extract HH:MM string from a time

    Parameters
    ----------
    value : datetime object
      Can be obtained from Time().to_datetime() or datetime specifically

    Returns
    -------
    HHMM : 

    Notes
    -----
    Created by Chun Ly, 11 August 2016
    '''

    HHMM = '%02i:%02i' % (value.hour, value.minute)
    return HHMM
#enddef

def get_sun_rise_set(dates, silent=True, verbose=False):
    '''
    Gets sunrise and sunset for a range of dates

    Parameters
    ----------
    dates : list or np.array of strings
      List of dates formatted as 'YYYY-MM-DD'. These are the observing dates and not
      UTC dates

    silent : boolean
      Turns off stdout messages. Default: False

    verbose : boolean
      Turns on additional stdout messages. Default: True
	  
    Returns
    -------

    Notes
    -----
    Created by Chun Ly, 11 August 2016
    '''
    
    if silent == False: print '### Begin mmt_ephemeris.get_sun_rise_set | '+systime()

    set0     = []; rise0     = []; set_astro = []; rise_astro = []; midnight  = [];
    #set_twil = []; rise_twil = []; 

    dates = [date +'T23:59:00' for date in dates]        # Assuming local time
    dates = [Time(date).to_datetime() for date in dates] # Convert to datetime format

    for ii in range(len(dates)):
        # print local_to_utc(Time(dates[ii]))
        time0 = Time(local_to_utc(Time(dates[ii]).to_datetime())) # Convert to UTC
        temp1 = obs.sun_set_time(time0, which='previous').to_datetime()
        temp2 = obs.sun_rise_time(time0, which='next').to_datetime()
        temp3 = obs.twilight_evening_astronomical(time0, which='previous').to_datetime()
        temp4 = obs.twilight_morning_astronomical(time0, which='next').to_datetime()
        set0.append(utc_to_local(temp1))
        rise0.append(utc_to_local(temp2))
        set_astro.append(utc_to_local(temp3))
        rise_astro.append(utc_to_local(temp4))
        midnight.append(utc_to_local(obs.midnight(time0, which='nearest').to_datetime()))

        if verbose == True and ii == 0:
            print 'Sunset:               {}'.format(set0[ii])
            print 'Sunrise:              {}'.format(rise0[ii])
            #print 'Twilight begins: {}'.format(set_twil[ii])
            #print 'Twilight ends: {}'.format(rise_twil[ii])
            print 'Astr. Twilight begin: {}'.format(set_astro[ii])
            print 'Astr. Twilight end:   {}'.format(rise_astro[ii])
            print 'Midnight:             {}'.format(midnight[ii])

        if silent == False: print '### End mmt_ephemeris.get_sun_rise_set | '+systime()

    return set0, rise0, set_astro, rise_astro, midnight        
#enddef

def table_sun_rise_set(dates, start_date, end_date, silent=True, verbose=False):
    '''
    Generate table of sunrise and set for a range of dates

    Parameters
    ----------
    dates : list or np.array of strings
      List of dates formatted as 'YYYY-MM-DD'. These are the observing dates and not
      UTC dates

    start_date: date object from datetime.date
      The start period for observing on MMT

    end_date: date object from datetime.date
      The end period for observing on MMT

    silent : boolean
      Turns off stdout messages. Default: False

    verbose : boolean
      Turns on additional stdout messages. Default: True
	  
    Returns
    -------

    Notes
    -----
    Created by Chun Ly, 11 August 2016
    Modified by Chun Ly, 12 August 2016
     - Added total hours
     - Added start_date and end_date input
    '''

    set0, rise0, set_astro, \
        rise_astro, midnight = get_sun_rise_set(dates, silent=silent,
                                                verbose=verbose)

    sunset0    = []; sunrise0   = []; set_astr0     = []; rise_astr0 = []
    set_twil0  = []; rise_twil0 = []; set_rise_time = []

    # Total up hours | + on 12/08/2016
    sum0 = datetime.timedelta(seconds=0) # rise-set time
    sum1 = datetime.timedelta(seconds=0) # rise-set time + 0.5hr on each end

    for ii in range(len(set0)):
        sunset0.append(str_hhmm(set0[ii]))
        sunrise0.append(str_hhmm(rise0[ii]))
        set_astr0.append(str_hhmm(set_astro[ii]))
        rise_astr0.append(str_hhmm(rise_astro[ii]))
        
        diff = rise0[ii] - set0[ii]

        # + on 12/08/2016
        sum0 += diff
        sum1 += diff + datetime.timedelta(minutes=60)
        set_rise_time.append(str(diff)[:5]) # Gets HH:MM string

    arr0   = [dates, sunset0, set_astr0, rise_astr0, sunrise0, set_rise_time] #, midnight]
    names0 = ['Date', 'set','twi.end','twi.beg', 'rise', 'set-rise'] #, 'Midnight']
    tab0 = Table(arr0, names=names0)

    # + on 12/08/2016
    print 'Total rise-set hours  : ', sum0.total_seconds() / 3600.0
    print 'Total observing hours : ', sum1.total_seconds() / 3600.0
    
    # + on 12/08/2016
    bus_days = np.busday_count( start_date, end_date) + 1
    print 'Expected hours : ', bus_days * 8.0

    return tab0
#enddef

#names0 = ['Date', 'Sunset','12deg set','18deg set', '18deg rise', '12deg rise', 'Sunrise', 'Time']
`

**Comment by bsipocz** [comment]
@astrochun - astroplan v0.2 is incompatible with astropy 1.3. You could either try to use it with astropy 1.2, or use the dev version of astroplan where everything is already been fixed.

@bmorris3 - Could we have a bugfix, 0.2.1 release at some point?

**Comment by astrochun** [comment]
@bsipocz, thanks for the info. I'll try v1.2 then with astroplan v0.2.
