### ISSUE TITLE
Place current field of view on sky map

### ISSUE THREAD

**Issue by ussserrr** [astropy/astroplan#299]
Hello!
It would be good if the plot of the current field of view can be placed on top of sky map with stationary objects like stars, galaxies and moving objects like planets, satellites, something like:
![map_last_2](https://cloud.githubusercontent.com/assets/20915411/25241287/225453b0-25fe-11e7-8f0f-344d4b36e6f2.png)
I've created this map by Astropy and Matplotlib, and then find Astroplan package with similar ideas and purposes.
Good luck!

**Comment by bmorris3** [comment]
Thanks for the tip! Pull requests are welcome any time.
