### ISSUE TITLE
plot_sky question

### ISSUE THREAD

**Issue by JamesMcKee** [astropy/astroplan#304]
I'm having trouble getting your tutorials that use plot_sky to work.  For example, running the source code for "Making a plot for one instance in time" (source code: plots-9.py) returns the following:

############################################################################
WARNING: OldEarthOrientationDataWarning: Your version of the IERS Bulletin A is 35.4 days old. For best precision (on the order of arcseconds), you must download an up-to-date IERS Bulletin A table. To do so, run:

>>> from astroplan import download_IERS_A
>>> download_IERS_A()
 [astroplan.utils]
Traceback (most recent call last):
  File "/home/jmckee/Desktop/plots-9.py", line 33, in <module>
    plot_sky(altair, observer, observe_time)
  File "/usr/local/lib/python2.7/dist-packages/astropy/utils/decorators.py", line 874, in plot_sky
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "/usr/local/lib/python2.7/dist-packages/astropy/units/decorators.py", line 130, in wrapper
    return wrapped_function(*func_args, **func_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/astroplan-0.3.dev936-py2.7.egg/astroplan/plots/sky.py", line 176, in plot_sky
    ax.scatter(az_plot, alt_plot, **style_kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 6308, in scatter
    transOffset=kwargs.pop('transform', self.transData),
  File "/usr/lib/pymodules/python2.7/matplotlib/collections.py", line 698, in __init__
    Collection.__init__(self, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/collections.py", line 119, in __init__
    offsets = np.asanyarray(offsets)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 583, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
ValueError: setting an array element with a sequence.
############################################################################

I get similar errors with the other tutorials using plot_sky. Could you help me understand what is wrong?

**Comment by bmorris3** [comment]
Could you include the source code that produces this error?

**Comment by JamesMcKee** [comment]
Hey Brett,

Thanks for the quick reply! The source code is:

import matplotlib.pyplot as plt
import astropy.units as u
from astropy.coordinates import EarthLocation, SkyCoord
from pytz import timezone
from astropy.time import Time

from astroplan import Observer
from astroplan import FixedTarget
from astroplan.plots import plot_sky

# Set up Observer, Target and observation time objects.
longitude = '-155d28m48.900s'
latitude = '+19d49m42.600s'
elevation = 4163 * u.m
location = EarthLocation.from_geodetic(longitude, latitude, elevation)

observer = Observer(name='Subaru Telescope',
               location=location,
               pressure=0.615 * u.bar,
               relative_humidity=0.11,
               temperature=0 * u.deg_C,
               timezone=timezone('US/Hawaii'),
               description="Subaru Telescope on Mauna Kea, Hawaii")

coordinates = SkyCoord('19h50m47.6s', '+08d52m12.0s', frame='icrs')
altair = FixedTarget(name='Altair', coord=coordinates)

import numpy as np

observe_time = Time('2000-03-15 17:00:00')
observe_time = observe_time + np.linspace(-4, 5, 10)*u.hour

plot_sky(altair, observer, observe_time)

# Note that you don't need this code block to produce the plot.
# It reduces the plot size for the documentation.
ax = plt.gca()
box = ax.get_position()
ax.set_position([box.x0, box.y0, box.width * 0.75, box.height * 0.75])

plt.legend(loc='center left', bbox_to_anchor=(1.25, 0.5))
plt.tight_layout()
plt.show()

**Comment by bmorris3** [comment]
That code worked for me without error. What version of astroplan are you using? See [tips here for updating](https://astroplan.readthedocs.io/en/latest/installation.html#id2).

**Comment by JamesMcKee** [comment]
I'm using astroplan v0.3 - the beginning of the output from astroplan.test() is:



============================= test session starts ==============================
platform linux2 -- Python 2.7.6, pytest-2.8.3, py-1.4.30, pluggy-0.3.1

Running tests with astroplan version 0.3.dev936.
Running tests in /usr/local/lib/python2.7/dist-packages/astroplan-0.3.dev936-py2.7.egg/astroplan.

Date: 2017-07-06T23:01:10

Platform: Linux-4.4.0-78-generic-x86_64-with-LinuxMint-17.3-rosa

Executable: /usr/bin/python

Full Python Version: 
2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]

encodings: sys: ascii, locale: UTF-8, filesystem: UTF-8, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.12.1
Scipy: 0.18.0
Matplotlib: 1.3.1
Pandas: not available
Astropy: 1.3.3
pytz: 2012c
pyephem: not available
matplotlib: 1.3.1
nose: 1.3.1
pytest-mpl: not available
Using Astropy options: remote_data.

rootdir: /usr/local/lib/python2.7/dist-packages/astroplan-0.3.dev936-py2.7.egg/astroplan, inifile:

**Comment by bsipocz** [comment]
@JamesMcKee - Your matplotlib version seems to be really old, could you try to upgrade it and try your code again?

**Comment by bmorris3** [comment]
I'm with @bsipocz – I just tested the source locally with python 2.7, mpl 2.0, numpy 1.10.4 and had no issues.

**Comment by JamesMcKee** [comment]
That worked! Thanks very much for the quick solution!

**Comment by bmorris3** [comment]
No problem @JamesMcKee, clear skies!
