### ISSUE TITLE
Incompatibilities with astropy 2.0

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroplan#306]
The latest coordinate improvements in astropy v2.0 means a few failures in astroplan. Currently they just show up in the dev build, but I'm about to update the CI tags of "stable" and "LTS" to point to 2.0 meaning that all of jobs in the travis matrix will start to fail.

**Comment by adrn** [comment]
What's failing? Can you point to some failing CI jobs?

**Comment by adrn** [comment]
Ah, I see here:
https://travis-ci.org/astropy/astroplan/jobs/251342146

We switched from string name keys to class keys. So anywhere you see 
```
frame_specific_representation_info['spherical']
```
needs to be changed to:
```
frame_specific_representation_info[coord.SphericalRepresentation]
```
