### ISSUE TITLE
listing observable times question

### ISSUE THREAD

**Issue by rrampall** [astropy/astroplan#308]
A little rusty but not new to python and fairly new to Astropy as an undergrad.  

I am trying to find out if my target has an observable transit from various locations (using Subaru for now) with an airmass constraint of two and an array of transit times on which to test the constraint. I am able to see if my target is ever_observable, always_observable, and the fraction of time (as well as the months_observable) it's observable based on the array of transit times. _But I would like to find out, specifically, during which of these times in the array is it observable through a logical array with the length of my time array or some such thing._ Is there something in the source code that can give me this output? Asking before I write a for loop that goes through the times one at a time. Thank you!

**Comment by bmorris3** [comment]
Hi @rrampall – you're right, the best way to go about doing this is to compute the observability in a loop over the transit times. 

There's a [branch in development](https://github.com/bmorris3/astroplan/tree/exoplanets) which does some of these calculations for eclipsing/transiting objects, but it has not yet been released in the master branch of astroplan.

**Comment by rrampall** [comment]
Thanks!
