### ISSUE TITLE
Move IPython notebook (Jupyter) examples to Sphinx docs.

### ISSUE THREAD

**Issue by jberlanga** [astropy/astroplan#31]
@astroplanners/astroplanners-contributors The plan is to move the contents of any IPython notebook (Jupyter) examples (`astroplan/examples/notebooks/`) into Sphinx files so that they reside on [`Astroplan`'s ReadTheDocs pages](https://astroplan.readthedocs.org/).

See comments from PR #16 [here](https://github.com/astroplanners/astroplan/pull/16#issuecomment-121722565) and [here](https://github.com/astroplanners/astroplan/pull/16#issuecomment-122045453).

**Comment by jberlanga** [comment]
@astroplanners/astroplanners-contributors 

P.S.  I can't seem to add labels after having created the issue--is this because I'm not a repo owner?

**Comment by eteq** [comment]
Yep, that's right, only people with commit rights can do that :(

**Comment by cdeil** [comment]
@jberlanga – Status?

(This issue is still open and on the 0.1 milestone, and we want to release today. If it's addressed, please close. If there's something to do, please make a PR today or move this to 0.2.)

**Comment by cdeil** [comment]
Actually ... I think this issue is addressed, closing it now.

(I had misread the diff in #42 ... I thought it was adding notebooks, but actually all notebooks from the repo have been removed.)
