### ISSUE TITLE
KeyError: 'spherical'

### ISSUE THREAD

**Issue by dokeeffe** [astropy/astroplan#310]
I think there must have been some changes in astropy's coord. I seem to be getting the following 
`le "/usr/local/lib/python3.5/dist-packages/astroplan-0.3.dev989-py3.5.egg/astroplan/target.py", line 238, in get_skycoord
    coords[0].frame_specific_representation_info['spherical']]
KeyError: 'spherical'`

I've tried building and installing locally from the latest MASTER branch but I still get the same error.
Thanks,
Derek

**Comment by bmorris3** [comment]
Hi @dokeeffe – sorry for the slow response time. This issue has been fixed as of #311.

**Comment by dokeeffe** [comment]
Thanks for fixing this!!! And apologies for not submitting a PR. Got too busy with other work.
