### ISSUE TITLE
Plan for version supports

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroplan#317]
I wonder about the plans about the python2/python3 supports along with numpy versions?

**Comment by bsipocz** [comment]
The question then of course is also relevant for astropy.

**Comment by bmorris3** [comment]
I think it's safe to assume that astroplan will migrate its support with astropy.

**Comment by bsipocz** [comment]
You mean for numpy? Or also with python? Is there a plan to maintain LTS support for 2 more years, or can we make the jump now and be python3 only? (tbh I'm not sure whether that's a viable option, as I have no info about the userbase).

**Comment by bmorris3** [comment]
The last time we really discussed it was way back in #28, we decided to keep py2 support for the time being. 

Quick Q for @wtgee – do I recall you saying at some point in the past that you need py2 support?

**Comment by bsipocz** [comment]
And how do you feel of dropping to np >=1.10 now? Not critical, and 2.0 support 1.9+, but could get rid of a few deprecation warnings with astropy 3.0.

**Comment by bmorris3** [comment]
I'm onboard. Let's do it. Shall I make a PR for it?

**Comment by bsipocz** [comment]
You should rather finish up the big PRs, I can deal with this in a moment.

**Comment by wtgee** [comment]
@bmorris3 No need for py2 here, thanks for checking though!

**Comment by bmorris3** [comment]
Going to resolve these comments in #387.
