### ISSUE TITLE
Observer.at_site not working

### ISSUE THREAD

**Issue by abostroem** [astropy/astroplan#337]
This command worked last week:
observatory = Observer.at_site('keck')

Now I get the following error:
/Users/bostroem/anaconda/lib/python3.5/site-packages/astroplan/observer.py in at_site(cls, site_name, **kwargs)
    259             raise ValueError("Location kwarg should not be used if "
    260                              "initializing an Observer with Observer.at_site()")
--> 261         return cls(location=EarthLocation.of_site(site_name), name=name, **kwargs)
    262 
    263     def astropy_time_to_datetime(self, astropy_time):

/Users/bostroem/anaconda/lib/python3.5/site-packages/astropy/coordinates/earth.py in of_site(cls, site_name)
    285             el = registry[site_name]
    286         except UnknownSiteException as e:
--> 287             raise UnknownSiteException(e.site, 'EarthLocation.get_site_names', close_names=e.close_names)
    288 
    289         if cls is el.__class__:

UnknownSiteException: "Site 'keck' not in database. Use EarthLocation.get_site_names to see available sites."

---------------------------------------------------

And when I try the following, I don't see anything:
ipdb> x = EarthLocation(19.827424*u.deg, (180-155.474940)*u.deg, 14000)
ipdb> x.get_site_names()
['example_site', 'greenwich']

**Comment by bsipocz** [comment]
@abostroem - What astropy and astroplan versions do you use?

**Comment by abostroem** [comment]
Excellent question!
astroplan.__version__
'0.2.1'
astropy.__version__
'1.3'

Let me update my astropy and add an update

**Comment by abostroem** [comment]
Ok, I get the same error with 
astropy.__version__
'2.0.2'

**Comment by bsipocz** [comment]
can you try astroplan 0.4? There were quite a work to put in since 0.2.1 to make it compatible with newer astropy.

**Comment by abostroem** [comment]
Where should I install it from? I tried: conda install astroplan=0.4 but it couldn't find the package

**Comment by bsipocz** [comment]
yes, the default conda doesn't have any of the affiliates. Try it from the astropy channel: `conda install -c astropy astroplan`

**Comment by abostroem** [comment]
I've updated to astroplan 0.4 and I have the same issue. Like I said, this worked for me last week. Is it possible there is some issue with the astropy database that is affecting the look-up?

**Comment by bsipocz** [comment]
if the database is not available the it will fall back on the default quasi empty one, and indeed that's happening. 
Try to download https://astropy.stsci.edu/data/coordinates/sites.json manually? 

(I got to run now, but will be back to keyboard in a few hours to check for a proper solution)

**Comment by abostroem** [comment]
Ok, so its definitely an issue with accessing the online site (I see the warning now, its been present above the traceback). I downloaded the link and put it in my astropy/coordinates/data directory so my code runs for now, but I suspect there is something underlying that needs to be fixed.

**Comment by bsipocz** [comment]
@abostroem - If you could check it again whether you still see the issue (our best guess is that it's transient with the data server), to also check with the latest astropy dev version. There is a fix for the data mirroring there, and would be great if you could confirm that it solves this issue, too.

**Comment by abostroem** [comment]
I still have the issue with my current version - how do I get the latest astropy dev version?

**Comment by anilseth** [comment]
I'm having what I'm guessing is a related issue with the Observer.at_site() command with Python 3.6.3+astropy2.0.3+astroplan0.4, however, with my Python 2.7.11 version (same astropy and astroplan) I don't have this problem.    

Here is the error message cut & paste from iPython.
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-1c26f66151b7> in <module>()
----> 1 subaru = Observer.at_site('subaru')

/Users/seth/anaconda/envs/py36/lib/python3.6/site-packages/astroplan/observer.py in at_site(cls, site_name, **kwargs)
    256             raise ValueError("Location kwarg should not be used if "
    257                              "initializing an Observer with Observer.at_site()")
--> 258         return cls(location=EarthLocation.of_site(site_name), name=name, **kwargs)
    259 
    260     def astropy_time_to_datetime(self, astropy_time):

/Users/seth/anaconda/envs/py36/lib/python3.6/site-packages/astropy/coordinates/earth.py in of_site(cls, site_name)
    337         get_site_names : the list of sites that this function can access
    338         """
--> 339         registry = cls._get_site_registry()
    340         try:
    341             el = registry[site_name]

/Users/seth/anaconda/envs/py36/lib/python3.6/site-packages/astropy/coordinates/earth.py in _get_site_registry(cls, force_download, force_builtin)
    477                         reg = get_downloaded_sites(force_download)
   478                     else:
--> 479                         reg = get_downloaded_sites()
    480                 except (six.moves.urllib.error.URLError, IOError):
    481                     # In Python 2.7 the IOError raised by @remote_data stays as

/Users/seth/anaconda/envs/py36/lib/python3.6/site-packages/astropy/coordinates/sites.py in get_downloaded_sites(jsonurl)
    130 
    131     if jsonurl is None:
--> 132         content = get_pkg_data_contents('coordinates/sites.json')
    133     else:
    134         content = get_file_contents(jsonurl)

/Users/seth/anaconda/envs/py36/lib/python3.6/site-packages/astropy/utils/data.py in get_pkg_data_contents(data_name, package, encoding, cache)
    714     with get_pkg_data_fileobj(data_name, package=package, encoding=encoding,
    715                               cache=cache) as fd:
--> 716         contents = fd.read()
    717     return contents
    718 

/Users/seth/anaconda/envs/py36/lib/python3.6/encodings/ascii.py in decode(self, input, final)
     24 class IncrementalDecoder(codecs.IncrementalDecoder):
     25     def decode(self, input, final=False):
---> 26         return codecs.ascii_decode(input, self.errors)[0]
     27 
     28 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19977: ordinal not in range(128)

**Comment by wtgee** [comment]
Marking Issue as stale and closing. Please re-open if still affected by this Issue.
