### ISSUE TITLE
local_sidereal_time returning attribute error

### ISSUE THREAD

**Issue by vlb9398** [astropy/astroplan#339]
**My Code to calculate LST at Kitt Peak:**
```python
newtime = Time('2018-1-16 18:00:00')
location = EarthLocation.from_geodetic(lon =-111.5947*u.deg, lat =31.95844*u.deg, height=2097.024*u.m)
kittpeak = Observer(location=location, name='kitt peak')
lst = kittpeak.local_sidereal_time(new time)
```

**The returned error:**
```AttributeError: 'EarthLocation' object has no 'lon' member```

I discovered that EarthLocation has been updated so that longitude is no longer used, however, even when using a workaround like the one below....
```python
kittpeak = Observer(longitude=-111.5947*u.deg, latitude=31.95844*u.deg, elevation=2097.024*u.m, name="Kitt Peak")
```
I still am returned with this same error. 

My versions for astropy: 2.0.3   and astroplan: 0.4

**Comment by bmorris3** [comment]
That's odd, I'm running astropy 2.0.3 and astroplan 0.4 and don't see that error. I don't understand why you'd see it...

One way around this problem for you might be to use the built-in site information: 
```
>>> EarthLocation.of_site('Kitt Peak')
<EarthLocation (-1994502.60430614, -5037538.54232911,  3358104.99690298) m>

>>> # or alternatively
>>> Observer.at_site('Kitt Peak')
<Observer: name='Kitt Peak',
    location (lon, lat, el)=(-111.6 deg, 31.963333333333342 deg, 2119.999999997953 m),
    timezone=<UTC>>
```

Do either of those options work for you? An internet connection will be required to resolve the locations.

**Comment by vlb9398** [comment]
@bmorris3 
Unfortunately it still returned the same error. I am also running this on anaconda, so perhaps running it on a python3 shell would be helpful? I can also try uninstalling and reinstalling.

**Comment by bmorris3** [comment]
It should work on both python 2 and 3. Try uninstalling and reinstalling astropy – that's where the machinery for this function lives.

**Comment by vlb9398** [comment]
It works!!! Uninstalled and reinstalled. There must have been something off about the anaconda install of astropy. Thank you for your help!

**Comment by bmorris3** [comment]
Great, @vlb9398! Happy planning, and clear skies.
