### ISSUE TITLE
Blocks with different constraint

### ISSUE THREAD

**Issue by educrot** [astropy/astroplan#341]
Hello, 
I am working on scheduling for exoplanet's detection. Astroplan is extremely useful, however, I was wondering if it is possible to schedule blocks with different constrains on the same night ? 

My aim is to constraint the second block of the night to a particular interval of time (using TimeConstraint) but not the first one. 

Thank you in advance for your help,
Cheers,
Elsa

**Comment by bmorris3** [comment]
Hi Elsa, 

The relevant [tutorial is written up here](https://astroplan.readthedocs.io/en/latest/tutorials/scheduling.html#creating-constraints-and-observing-blocks). Let me know if that helps you figure it out, I'll keep the issue open just in case you have more questions.
