### ISSUE TITLE
Detection of pyephem in conftest.py is wrong or can be removed

### ISSUE THREAD

**Issue by Universebenzene** [astropy/astroplan#343]
Line 43 of `conftest.py`: 
```python
    PYTEST_HEADER_MODULES['pyephem'] = 'pyephem'
```

it should be `PYTEST_HEADER_MODULES['pyephem'] = 'ephem'` , or it won't detect the newest version of pyephem. Or if the module is not necessary for astroplan, this detection can be removed.

**Comment by bsipocz** [comment]
Thanks @Universebenzene for raising this. This import is purely cosmetic and only used to populate the printed out header before the test run starts. I'll fix it nevertheless.

For more context: Actually we don't actively use pyephem in the CI test suite but the results from it are hard wired, and the few additional test function that uses it are only run locally (and indeed importing `ephem`).
