### ISSUE TITLE
Create a custom cycler for linestyles

### ISSUE THREAD

**Issue by abostroem** [astropy/astroplan#361]
For a large list of objects, you want to distinguish objects after the colors start repeating. Create a custom cycler that cycles through linestyles.

**Comment by bmorris3** [comment]
Hi @abostroem! I'm closing as stale, mostly because you can now take advantage of packages like [cycler](https://matplotlib.org/cycler/) if the matplotlib defaults don't cut it. Please reopen if necessary!
