### ISSUE TITLE
tkinter required to test()

### ISSUE THREAD

**Issue by bernie-skipole** [astropy/astroplan#376]
After installation, got this error when running
astroplan.test()
on linux mint:

    try:
>       import _tkinter
E       ImportError: No module named '_tkinter'

/usr/lib/python3.5/tkinter/__init__.py:36: ImportError

Solved with apt-get install python3-tk
Installation document should perhaps mention this dependency

**Comment by bsipocz** [comment]
I believe this is not an astroplan issue, but the very same reported here for matplotlib: https://github.com/matplotlib/matplotlib/issues/9017

Could you try to change your backend as suggested there?

**Comment by bmorris3** [comment]
@bernie-skipole Did @bsipocz's tip work for you?

**Comment by bernie-skipole** [comment]
Did not try it, as I had already solved the problem, as stated in my
original post:

"Solved with apt-get install python3-tk"

This is more of an installation documentation issue, which should mention
this dependency.
