### ISSUE TITLE
Axis coordinate problem

### ISSUE THREAD

**Issue by kobe90** [astropy/astroplan#383]
Hello,
I am trying to use the astroplan library to build finding charts.

I’ve tried to follow this guide
https://astroplan.readthedocs.io/en/latest/tutorials/plots.html#plots-sky-charts
in particular, I used the example I found in the very last section ‘Finder Chart/Image’.
In order to better understand the library, I’ve tried also different coordinates to download the relative archive images.
I’ve tried in particular this:
ra, dec = 197.11, 52.23
The point is that the image I get is somehow strange when considering the x axis (I’ve overplotted some circles for my personal usage):
![figure_1](https://user-images.githubusercontent.com/32132854/48915488-20011800-ee7f-11e8-8d8d-cf4691ab5481.png)
As you can appreciate, the scale seems to be a little bit wrong, also considering that the download image is supposed to be a square one.
Please, tell me if I did something wrong.

Thank you in advance.

P.S.:The 2’ scale bar has been drawn using the formula:
bar = AnchoredSizeBar(ax.transData, 2./(60*np.abs(hdu.header['CDELT1'])), "2'", 3)
ax.add_artist(bar)  

being ax and hdu the same reported in the Finder Chart/Image section of https://astroplan.readthedocs.io/en/latest/tutorials/plots.html#plots-sky-charts . The second argument of AnchoredSizeBar is the length of the bar and hdu.header['CDELT1’] is the pixel scale as specified in the header attached to the image.

**Comment by bmorris3** [comment]
Hi @kobe90! Could you share the full code used to produce the plot, so we can try to debug?

**Comment by bmorris3** [comment]
Hmmm this seems tricky. It looks like the scale bar is the correct length for the vertical axis (RA) but not the horizontal axis. I can't identify what's incorrect here, but I can say that the scale on the horizontal axis is already clearly marked by the `xticklabels` – are they insufficient for your purposes?

**Comment by bmorris3** [comment]
I'm going to see if we get lucky and can tag-team with @astrofrog who is the mastermind behind much of wcsaxes – do you have any tips for this particular issue?

**Comment by kobe90** [comment]
Yes, my guess is that maybe the pixel scale is wrong on the x-axis, since it is always reported to be the same of that of the y-axis. This is not possible, since the image is a square but you have almost 20' on the x axis and almost 10' on the y-axis. What you think?

**Comment by bmorris3** [comment]
I agree, something about that is fishy.

**Comment by astrofrog** [comment]
@kobe90:

> This is not possible, since the image is a square but you have almost 20' on the x axis and almost 10' on the y-axis. What do you think?

The x-axis has RA, not angle - it might subtend 10 minutes of RA, but that's 10 * cos(dec) arcminutes.

I think you are also missing a cos(dec) factor when figuring out the length of the scalebar.

**Comment by rmathar** [comment]
As observed by kobe90, the CDELT1 of a standard WCS coordinate system is the delta in the product of RA*cos(delta), which is the natural unit work with uniform scales on both axes. To get a value that is correct (for a small patch on the sky where delta is almost constant) one must divide through the cosine of delta (which is smaller than 1) to get a bar that is as long as the desired angle. That problem could for example be removed by using CDELT2 and printing that bar vertically, as such a trigonometric scaler is absent on the DEC axis.

**Comment by rmathar** [comment]
As far as I can tell the question is fully answered and just a misunderstanding of what sky coordinates really mean. IMHO the issue can be closed without any further action on the astroplan side.
