### ISSUE TITLE
Feature request - notebook tutorials

### ISSUE THREAD

**Issue by robmarkcole** [astropy/astroplan#384]
Not an issue, rather a request, that the tutorials be made available as Jupyter notebooks.
Thanks
Robin

**Comment by bmorris3** [comment]
Hi Robin! 

May I suggest the following [notebook tutorial](https://github.com/UWashington-Astro300/astroplan-in-the-classroom)?

**Comment by robmarkcole** [comment]
Thanks for the suggestion, however my idea was to replace/complement the .rst files in https://github.com/astropy/astroplan/tree/master/docs/tutorials It would be nice to just clone the repo and use the notebooks, rather than have to copy-past to a fresh notebook.

**Comment by bsipocz** [comment]
@robmarkcole - I'm not a maintainer here, but keeping notebooks in a library repo (especially instead of documentation) opens large cans of worms for all kind of reasons. 
However having notebooks somewhere central, maybe you could suggest to have an astroplan one in https://github.com/astropy/astropy-tutorials/?

**Comment by robmarkcole** [comment]
Hi @bsipocz I wasn't proposing to replace the docs with notebooks (although I believe there are tools to do that) but just to complement the tutorials. I am wondering if the CI system can be configured to re-run the notebooks to ensure they don't break..? Thanks for the link to the astropy tutorials, but I would usually expect notebooks to be in the parent repo. TBH I've been aware of astropy for a year now but only learned in this thread that there are notebook tutorials in another repo. I will close this request and perhaps it sparks a few ideas. Thanks

**Comment by bsipocz** [comment]
You're right that we definitely need to make a better job to advertise the tutorials.
