### ISSUE TITLE
Wrong range for Observer.parallactic_angle

### ISSUE THREAD

**Issue by rmathar** [astropy/astroplan#385]
Astroplan 0.4 (in use with astropy 2.0.9 in case that matters) is having a problem with Observer.parallactic_angle() .
This wraps the angle into the -90..+90 range, whereas the parallactic angle should be in the -180..+180 range.
See e.g. https://en.wikipedia.org/wiki/Position_angle. The error is obviously that the np.arctan() function was used where the 2-argument np.arctan2() is in order.

**Comment by bmorris3** [comment]
Fixed in #386.
