### ISSUE TITLE
Revise test matrix

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroplan#387]
There has been some update in upstream versions since the latest matrix revision, e.g. 

* we should tests with Python 3.7

* there are quite a few untested numpy combinations, too that can be spread over the matrix.

* Also, changing the numpy dev testing to be with python3 I feel would make much sense.

* One of the python3 egg tests can be dropped.

* codestyle check to be moved up to the initial tests, if we are failing a build with it, it should be done sooner rather than later to avoid wasting too much CI resources

**Comment by bmorris3** [comment]
I think most/all of these points have been addressed since this issue was posted, most recently via #493.
