### ISSUE TITLE
phase angle between moon and sun reported by moon_phase is real phase angle ([0,pi]), not ([0,2pi])

### ISSUE THREAD

**Issue by aakepley** [astropy/astroplan#391]
The documentation for moon_phase currently states the following:

https://github.com/astropy/astroplan/blob/4edc831ddbb104bbc0fc3e971764c3a3e703bd64/astroplan/observer.py#L1490

However, when you plot the phase over an entire moon cycle it travels over the range [0,pi], with the new moon as pi.

**Comment by aakepley** [comment]
Test case and plot below: 
```

from astroplan import Observer
from astropy.time import Time
from astropy.coordinates import EarthLocation
import matplotlib.pyplot as plt

mjd = 58416.188

location = EarthLocation.from_geodetic(lon='-79d50m23.406s',lat='38d25m59.236')
gbt = Observer(location=location, elevation=807.43*u.m,name='gbt',timezone='US/Eastern')
time = Time(mjd,format='mjd')

period_moon = 29.530589
x = np.linspace(0,1,1000)
date_range = time+x*period_moon
phase = gbt.moon_phase(date_range)
illum = gbt.moon_illumination(date_range)

plt.plot(date_range.mjd-date_range[0].mjd,phase,label='phase')
plt.plot(date_range.mjd-date_range[0].mjd,illum, label='illumination')
plt.legend()

plt.savefig('moon_phase.pdf')

```

**Comment by bmorris3** [comment]
Thanks for catching that @aakepley. So the appropriate fix is to correct the documentation to say `pi` rather than `2pi`, yes?

**Comment by aakepley** [comment]
Yes. What you have just calculates the angle between the Moon-Sun vector and the Moon-Earth vector which is fine for most applications. Unfortunately, my application cares about whether the moon is first quarter or last, which your calculation doesn't do.  @low-sky took a look at your code and there doesn't appear to be an easy to get this out nicely, so I'm going to brute force the calculations needed.

**Comment by aakepley** [comment]
wrong button click. doh.

**Comment by low-sky** [comment]
I'll add that the calculation just produces the standard definition of "phase angle" which isn't the angle of the moon travelling around the Earth.  It would be fine to just call it `0 to pi` on the docs and we'll brute force solve for the elongation = 0 point to find time since new moon.
