### ISSUE TITLE
Failure in rise, set and transit time computations

### ISSUE THREAD

**Issue by talensgj** [astropy/astroplan#398]
The next twilight computation fails in the following code snippet because the next occurrence falls just outside the 24 hour window that is searched. I encountered this bug while plotting with brightness_shading=True and it is presumably an issue for all similar methods that search a 24-hour window for rise, set or transit times.

```python
import astroplan

import astropy.units as u
from astropy.time import Time

time = Time('2019-11-22T11:20:05.799')

observer = astroplan.Observer(longitude=-71.1527*u.deg, latitude=45.4558*u.deg)

time0 = observer.twilight_morning_civil(time, which='previous')
time1 = observer.twilight_morning_civil(time, which='next')
time2 = observer.twilight_morning_civil(time+1*u.hour, which='next')

time0.format = time.format
time1.format = time.format
time2.format = time.format

print(time)
print(time0)
print(time1)
print(time2)
```

**Comment by bmorris3** [comment]
While this is a corner case, which occurs only when the reference `time` is awfully close to a sunrise or sunset, this is a case that should be handled gracefully in astroplan. 

When I run the above example, `time0` is returned as `MAGIC_TIME`, which is the first sign that something is going wrong. The `TargetNeverUpWarning` is raised, which indicates that the target rises just a bit more than 24 hours after the specified time, as indicated in the issue.

**Comment by bmorris3** [comment]
As of #435 this has been fixed 🎉. The example script above now prints: 
```
WARNING: TargetNeverUpWarning: Target with index 0 does not cross horizon=-6.0 deg within 24 hours [astroplan.observer]
2019-11-22T11:20:05.799
2019-11-22T11:19:55.993
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
--
2019-11-23T11:21:09.701
```
To get the latest dev version of astroplan, [follow these installation instructions](https://astroplan.readthedocs.io/en/latest/installation.html#id2).
