### ISSUE TITLE
Assertion error in test_schedule_insert_slot

### ISSUE THREAD

**Issue by nflagey** [astropy/astroplan#406]
Hey there,
I'm new to Astroplan (and quite new to Python overall). I have run the astroplan.test() but keep getting an Assertion Error for test_schedule_insert_slot.
I am using Python 3.6.8 with Anaconda. I have Astropy 3.1.2 and Astroplan 0.4

The error points at:
>       assert end_time - duration == start

It seems like this issue was fixed in #342 which modified to code into:
         assert (end_time - duration).jd == start.jd

For some reason, it seems like I do not have the right version running ... how come?

I get the error whether I run the test in iPython and Python in my terminal, in a Jupyter Notebook, and in PyCharm.

**Comment by bsipocz** [comment]
@nflagey - astroplan hasn't been released for a while, you if you installed your version with pip or conda you most likely don't have the fix for issue #342.

To try the development version you can try this:
`pip install --upgrade https://github.com/astropy/astroplan/archive/master.zip`

**Comment by nflagey** [comment]
Thanks @bsipocz !
I grabbed the newest version of `test_scheduling.py` and the test is now passed ;)

I'll continue playing with Astroplan ... I'm wondering if we could use it at the observatory I'm working for. Anybody has implemented Astroplan as their official scheduler yet?

**Comment by bsipocz** [comment]
I know about MMT using it, and GOTO. There may be others, too.

**Comment by bsipocz** [comment]
Also,  could you please close the issue as you have confirmed it's being solved? Thanks.

**Comment by bsipocz** [comment]
@nflagey - If you run into issues while trying this out feel free to either raise them here, or come and join the astropy slack: http://joinslack.astropy.org/
