### ISSUE TITLE
Need high-level docs.

### ISSUE THREAD

**Issue by jberlanga** [astropy/astroplan#41]
Hi @astroplanners/astroplanners-contributors,

I'm starting to write the docs and would like some input for what you would like to see/not see.

My starting point is to take the current RTD site and add: 

* A `Tutorials` page with separate pages for a few different use cases. 
* `Getting Started` would have a section explaining how the different types of objects correspond to observing concepts (e.g., target info contained in a `Target` object, etc.) and the way that you extract attributes/use methods in general.  Perhaps also a section for basic tasks (such as creating `Observer` and `Target` objects).
* A `How to..` page linking to others that explain how to do specific things (e.g., extract alt/az info).
* A `Plots/Visualization` page containing basic examples and linking to a detailed run-through of all the options for each plotting function.

**Comment by cdeil** [comment]
This was adressed in #42.

If someone has further suggestions, please open a new issue or PR.
