### ISSUE TITLE
Release v0.5?

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#415]
@bmorris3 or anyone - would it be possible to release a new stable version of astroplan now or soon?

I got a question about some issue from a user, and it turned out, it was already fixed in master.

The last release is v0.4 from Oct 2017:
https://pypi.org/project/astroplan/#history

Maybe close the v0.3 milestone, and introduce milestones for 0.5 and 0.6?
https://github.com/astropy/astroplan/milestones
I find using milestones is helpful for devs, but it's also useful for outsiders like me to see if / when a new release is planned.

**Comment by bmorris3** [comment]
@cdeil You got it! Sorry for the delay 😄

**Comment by bmorris3** [comment]
Released on pypi! @mwcraig – may I trouble you for a reminder on how to update the conda-forge correctly for astroplan v0.5?

**Comment by cdeil** [comment]
@bmorris3 - awesome, thanks!

pip install and running tests works for me on on macOS for the new v0.5.

**Comment by mwcraig** [comment]
@bmorris3 the conda forge bot already opened this: https://github.com/conda-forge/astroplan-feedstock/pull/5
