### ISSUE TITLE
IERS A table

### ISSUE THREAD

**Issue by astrom-tom** [astropy/astroplan#417]
Dear all,

When trying to download the IERS_A table I got the following answer:

WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all and http://toshi.nofs.navy.mil/ser7/finals2000A.all, using local IERS-B: <urlopen error [Errno -2] Name or service not known>;<urlopen error timed out> [astropy.utils.iers.iers]

I do not know if it is because the website is down or what. 

Also, the IERS_A_URL and IERS_A_URL_MIRROR have exactly the same url. Is that normal?

Thanks!

R.

**Comment by bmorris3** [comment]
This itermittantly happens on occasion when the server and its backup mirror fails – if you still get this error tomorrow, let us know!

**Comment by astrom-tom** [comment]
Seems to be working now!
Thanks!
