### ISSUE TITLE
Importing anything from astroplan result in failure

### ISSUE THREAD

**Issue by gnthibault** [astropy/astroplan#425]
Dear all, I recently found myself unable to use astroplan. Simply importing Observer class within ipython result in an error:

```
In [1]: from astroplan import observer                                                                                                                                                                      
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-648acb6867e1> in <module>
----> 1 from astroplan import observer

~/projects/RemoteObservatory/venv/lib/python3.6/site-packages/astroplan/__init__.py in <module>
     30     from .periodic import *
     31 
---> 32     get_IERS_A_or_workaround()

~/projects/RemoteObservatory/venv/lib/python3.6/site-packages/astroplan/utils.py in get_IERS_A_or_workaround()
     55     """
     56     if IERS_A_in_cache():
---> 57         iers.IERS.iers_table = _get_IERS_A_table()
     58     else:
     59         Time._get_delta_ut1_utc = _low_precision_utc_to_ut1

~/projects/RemoteObservatory/venv/lib/python3.6/site-packages/astroplan/utils.py in _get_IERS_A_table(warn_update)
     89     """
     90     if IERS_A_in_cache():
---> 91         table = iers.IERS_Auto.open()
     92         # Use polar motion flag to identify last observation before predictions
     93         index_of_last_observation = ''.join(table['PolPMFlag_A']).index('IP')

~/projects/RemoteObservatory/venv/lib/python3.6/site-packages/astropy/utils/iers/iers.py in open(cls)
    640             return cls.iers_table
    641 
--> 642         cls.iers_table = cls.read(file=filename)
    643         cls.iers_table.meta['data_url'] = str(conf.iers_auto_url)
    644 

~/projects/RemoteObservatory/venv/lib/python3.6/site-packages/astropy/utils/iers/iers.py in read(cls, file, readme)
    500 
    501         # Combine the A and B data for UT1-UTC and PM columns
--> 502         table = cls._combine_a_b_columns(iers_a)
    503         table.meta['data_path'] = file
    504         table.meta['readme_path'] = readme

~/projects/RemoteObservatory/venv/lib/python3.6/site-packages/astropy/utils/iers/iers.py in _combine_a_b_columns(cls, iers_a)
    463         #              Bull. A UT1-UTC values
    464         is_predictive = (table['UT1Flag_A'] == 'P') | (table['PolPMFlag_A'] == 'P')
--> 465         table.meta['predictive_index'] = np.min(np.flatnonzero(is_predictive))
    466         table.meta['predictive_mjd'] = table['MJD'][table.meta['predictive_index']]
    467 

<__array_function__ internals> in amin(*args, **kwargs)

~/projects/RemoteObservatory/venv/lib/python3.6/site-packages/numpy/core/fromnumeric.py in amin(a, axis, out, keepdims, initial, where)
   2744     """
   2745     return _wrapreduction(a, np.minimum, 'min', axis, None, out,
-> 2746                           keepdims=keepdims, initial=initial, where=where)
   2747 
   2748 

~/projects/RemoteObservatory/venv/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     88                 return reduction(axis=axis, out=out, **passkwargs)
     89 
---> 90     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     91 
     92 

ValueError: zero-size array to reduction operation minimum which has no identity

```

Version of astro*** modules:
astroplan==0.5
astropy==3.0.4
astroquery==0.3.10

Thank you in advance for your help

**Comment by wtgee** [comment]
I'm pretty sure this is all part of the IERS issues as mentioned in #418. The official servers should be down as of today and no fix has been put in yet.

**Comment by gnthibault** [comment]
Ouch, ok thank you, waiting for a workaround then...

**Comment by bmorris3** [comment]
@gnthibault Thanks for the heads up, this is a realization of the worst-case scenario for the problems raised in astropy/astropy#9427 and temporarily fixed in astropy/astropy#9443. The need for longer-term fix documented in astropy/astropy#9453. 

It looks to me like this requires an astroplan fix _right now_. I'm going to investigate getting my own version of #418 working with a fix for the [matplotlib error](https://github.com/astropy/astroplan/pull/418#issuecomment-544919325) that's delaying the release of that PR. 

This may not be a problem for people who have a recent version of the IERS tables – I can still import astroplan without error.

This might mean that the next version of astroplan should require the latest version of astropy in order to pick up the IERS fix. Looping in @bsipocz and @pllim for their advice – when is the next release of astropy going to be available via pip, for example?

**Comment by gnthibault** [comment]
Thank you a lot @bmorris3  ! I can wait for the astropy fix though if astroplan is supposed to work out of the box with next astropy release

**Comment by pllim** [comment]
`astropy` 4.0 does not have a set release date yet but tentatively by the end of the year. Check https://github.com/astropy/astropy/wiki/Release-Calendar from time to time to see if it is posted. Thanks for your patience!

**Comment by dokeeffe** [comment]
Is there a workaround where you can override the mirror? Would it be possible for someone to post an example of how to do this? Thanks

**Comment by AnthonyHorton** [comment]
> `astropy` 4.0 does not have a set release date yet but tentatively by the end of the year. Check https://github.com/astropy/astropy/wiki/Release-Calendar from time to time to see if it is posted. Thanks for your patience!

Should point out that the IERS fix for astropy was released two days ago as v3.2.3 (http://docs.astropy.org/en/stable/changelog.html#full-changelog), no need to wait for 4.0. The remaining problems are now with astroplan. We're waiting on #418 & #426.

**Comment by bmorris3** [comment]
One workaround may be the following; in a clean terminal, run the following in a python terminal:

```python
from astropy.utils import iers
iers.IERS_A_URL = 'ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all'
from astroplan import download_IERS_A
download_IERS_A()
```

Please let me know if this works ASAP!

**Comment by gnthibault** [comment]
I had also changed astropy for the 3.2.3, It worked ! thank you !

**Comment by gnthibault** [comment]
I had also changed astropy for the 3.2.3, It worked ! thank you !

Le mar. 29 oct. 2019 à 09:18, Brett M. Morris <notifications@github.com> a
écrit :

**Comment by dokeeffe** [comment]
> ```python
> from astropy.utils import iers
> iers.IERS_A_URL = 'ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all'
> from astroplan import download_IERS_A
> download_IERS_A()
> ```

I'm getting a timeout from that URL but I think its being blocked by my corporate network. I'll try again when I get home and let you know. Thanks!!!

**Comment by bmorris3** [comment]
@dokeeffe Good luck 👍

**Comment by dokeeffe** [comment]
@bmorris3 YES! That worked. Thanks a million!!
