### ISSUE TITLE
astroplan import issue

### ISSUE THREAD

**Issue by alexmaragko** [astropy/astroplan#432]
I have installed the astroplan package through conda (version 4.7.12).

While the package appears to be installed without issues, when I open ipython (through the astroconda environment, https://astroconda.readthedocs.io/en/latest/) and import astroplan, I get the following error message: "error: db type is dbm.gnu, but the module is not available".

I'm on Linux Mint, and my Python and package versions (as obtained from the astroconda environment) are the following:
Python 3.7.4
Numpy 1.16.4
Astropy 3.2.1

**Comment by bmorris3** [comment]
It looks like the solution might be [this](https://stackoverflow.com/a/48676738). 

If that doesn't work, perhaps you can share with us the full traceback of the error?

**Comment by bmorris3** [comment]
This issue seems related to astropy/astropy#9607. Please continue discussion there.

**Comment by alexmaragko** [comment]
Thanks. clear_download_cache() did the trick.
