### ISSUE TITLE
use_local_tz is not using the local timezone

### ISSUE THREAD

**Issue by keflavich** [astropy/astroplan#452]
Oops - looks like the timezone shifts the plot so that midnight is on the plot edges, but the numbers on the X-axis have not changed.

![image](https://user-images.githubusercontent.com/143715/72482477-cf0f5a00-37cb-11ea-9b6f-fe2ecff750df.png)

![image](https://user-images.githubusercontent.com/143715/72482489-d9c9ef00-37cb-11ea-968e-5f50fbb64f1b.png)

**Comment by bmorris3** [comment]
Closed in [#455](https://github.com/astropy/astroplan/pull/455).
