### ISSUE TITLE
determining n_eclipses between two times

### ISSUE THREAD

**Issue by jpdeleon** [astropy/astroplan#457]
I use `EclipsingSystem.next_primary_eclipse_time` to predict primary transits between two specified datetimes e.g. `dt1`, `dt2`. Since `dt1` is only required as input, what is the best way to determine `n_eclipses` to make sure sufficient number of transits are computed from `dt1` until it reaches `dt2`? I currently use `n_eclipses`=1/`period`x`baseline` if `period`<1 else 1.5x`baseline`, where baseline is the difference between `dt1` and `dt2`. Do you suggest a better way to determine `n_eclipses` for this purpose?

**Comment by bmorris3** [comment]
I normally do something just like your proposed method. Is that working for you?

**Comment by jpdeleon** [comment]
Hi Brett, normally this works fine except for ultra-short period (e.g. 0.05 d) ones. They're rare so for normal transit configurations, this works from experience.

**Comment by bmorris3** [comment]
From the NASA Exoplanet Archive, the shortest known period planet is PSR J1719-1438 b at P=0.09 d. The next shortest is 0.17 d, so for now at least, it would seem that we support >99.9% of known planets. If you'd like to create a PR to support short period planets that theoretically might exist, your PR would be welcome, but I'm closing this issue for now. Thanks!
