### ISSUE TITLE
How should I get the "value" of altitude or airmass?

### ISSUE THREAD

**Issue by TakuNishiumi** [astropy/astroplan#461]
Astroplan's `plot_altitude` gives us a plot of altitude and/or airmass.
However, I would like to get the value of the altitude on the specific time.
How should I get this value?

**Comment by bmorris3** [comment]
See the [docs here](https://astroplan.readthedocs.io/en/latest/tutorials/summer_triangle.html#airmass):
```
observer.altaz(time, target).secz # returns airmass approximation
```

**Comment by TakuNishiumi** [comment]
Great!
Thank you!!
