### ISSUE TITLE
Compatibility with astropy 4.x

### ISSUE THREAD

**Issue by wtgee** [astropy/astroplan#479]
`astroplan` is currently not working with newer `astropy` (`> 4.0`?), which is starting to affect a number of users, self included.

Seems to mostly be issues with the download and caching mechanisms. 

Comes from:

@bmorris3 - I have received user feedback (in addition to this PR and @keflavich's in astropy core) that astroplan is not compatible with the latest astropy, so I suppose having an ETA for a new bugfix release would be helpful for them to plan ahead.

_Originally posted by @bsipocz in https://github.com/astropy/astroplan/pull/471#issuecomment-707256870_

**Comment by wtgee** [comment]
I might try to jump in on this unless someone else has an over-abundance of time. This is starting to impact a number of repos I'm working on.

**Comment by bmorris3** [comment]
Please do @wtgee, thanks for stepping up! I'm just returning from paternity leave and I'm a bit swamped.

**Comment by mireianievas** [comment]
In particular, astropy changed from _get_download_cache_locs to  _get_download_cache_loc, which has a different input and output. For now just dirty copying the _get_download_cache_locs from the older astropy did the job to at least import astroplan, but I'm not fully sure it will work.
