### ISSUE TITLE
PEP cleanup

### ISSUE THREAD

**Issue by wtgee** [astropy/astroplan#482]
There is a lot of code throughout the repo that doesn't conform to PEP. Just wanted to put a generic Issue here as a reminder to get it cleaned up.

**Comment by bmorris3** [comment]
Hi @wtgee! Do you think our very broad [flake8](https://github.com/astropy/astroplan/blob/main/tox.ini#L100) testing is sufficient? That's more or less the standard in the astropy community at the moment.
