### ISSUE TITLE
Determine requirements

### ISSUE THREAD

**Issue by wtgee** [astropy/astroplan#483]
We haven't visited the requirements for the module for a bit. We have `astropy` set to the old `1.x` branch and some issues with matplotlib (see #468 and #481).

* [ ] Remove python2 stuff (?)
* [ ] Determine minimum astropy needs
* [ ] Remove the `matplotlib<3.3` pinning from #481 
* [ ] ....

**Comment by bmorris3** [comment]
Hi @wtgee – it looks like some of these issues have been addressed elsewhere. Is there anything lingering?

**Comment by wtgee** [comment]
LGTM, will close and if I see anything specific will open a separate Issue. Thanks!
