### ISSUE TITLE
Return type from moon_phase_angle (astroplan v0.6)

### ISSUE THREAD

**Issue by trmrsh** [astropy/astroplan#488]
Hello, I installed astroplan v0.6 which is distributed within my linux distro (fedora 32), so apologies if this is already outdated by the latest version.

Very minor issue: the return from moon_phase_angle is stated (using pydoc) to be "float", in radians, but it seems to be an astropy.units.Quantity (so there came a point in my code where treating it as a float failed).

Thanks, Tom

**Comment by bmorris3** [comment]
Thanks for this note, you're right! 

Fixed in 069763f.
