### ISSUE TITLE
Documentation is out of date on ReadTheDocs

### ISSUE THREAD

**Issue by mwcraig** [astropy/astroplan#495]
The stable version of the documentation on RTD points to version `0.4.1.dev1090`; the latest version seems to point to `0.7.dev1007`. Both are out of date, I think.

This may ( or may not) be related to the warnings described here: https://github.com/astropy/astroplan/pull/493/files#r550805421

Actually, looking at the build log it appears a new build hasn't triggered in a year, so something more fundamental is going on: https://readthedocs.org/projects/astroplan/builds/

**Comment by bmorris3** [comment]
Thanks so much for this heads up, investigating now.

**Comment by bmorris3** [comment]
Fixed! https://astroplan.readthedocs.io/en/latest/
