### ISSUE TITLE
Shouldn't rise and set be constant over a 24hr?

### ISSUE THREAD

**Issue by mirosaide** [astropy/astroplan#509]
Hi,

I am calculating the rise and set of Barnard's star for different locations on the globe.
Somenthing that is letting me confused is the fact that the rise and set are not constant over 24hr period.

Am I doing something wrong or it's just the way it is.

The code is below:

``
from astropy.visualization import astropy_mpl_style, quantity_support
plt.style.use(astropy_mpl_style)
quantity_support()
import astropy.units as u
from astropy.time import Time
from astropy.coordinates import SkyCoord, EarthLocation, AltAz
from astroplan import Observer, FixedTarget
from astropy.time import Time
from astroplan import download_IERS_A
download_IERS_A

time = Time("2020-05-12 00:00:00",format='iso')
target = SkyCoord.from_name("Barnard's star")
Location = Observer(latitude=42.248*u.deg, longitude=-122.567*u.deg)
star_rise_time = Location.target_rise_time(time, target, which='nearest')
star_set_time = Location.target_set_time(time, target, which='nearest')

**Comment by bmorris3** [comment]
Hi, 

Does this FAQ page answer your question? 

https://astroplan.readthedocs.io/en/latest/faq/precision.html#why-is-my-target-above-below-the-horizon-at-the-rise-set-time

**Comment by mirosaide** [comment]
It Does. Thank you.
