### ISSUE TITLE
Add `plot_sky_24hr`

### ISSUE THREAD

**Issue by eteq** [astropy/astroplan#51]
As discussed in our telecon today, we merged #30 *without* any special behavior for scalar inputs (they are just treated like single-element vectors).  Instead, there should be a new function called something like `plot_sky_24hr` or `plot_sky_night` or `plot_sky_somethingelse` which plots a target +/- 12 hr from a provided time.  This should actually use `plot_sky` internally, probably just accepting a `target`, `time` (which now *must* be a scalar - should raise an exception otehrwise), and any further keyword arguments would just be passed to `plot_sky` using ``**kwargs``.

Additional enhancements discussed in the telecon:
* Include a `delta` keyword (which defaults to 1 hour), controlling the spacing between the points.
* Add a keyword for annotations showing the direction of rise/set like https://github.com/astroplanners/astroplan/pull/30#issuecomment-127415575 
* Add a keyword to add an extra marker for the "middle" time (i.e., the time that actually was passed in).

**Comment by cdeil** [comment]
@jberlanga , @eteq - Status?

Is this feature request addressed by the current [plot_sky](http://astroplan.readthedocs.org/en/latest/api/astroplan.plots.plot_sky.html) function?
If not, does someone have time to address it today or should we move the issue to 0.2?

**Comment by jberlanga** [comment]
@cdeil -- I think we should move this to 0.2.

**Comment by cdeil** [comment]
@jberlanga – You should have permissions now to label and move milestones yourself ... go ahead!

**Comment by bmorris3** [comment]
This was closed by #124.
