### ISSUE TITLE
observer.target_rise_time(): Optional argument to throw TargetAlwaysUpWarning as an exception?

### ISSUE THREAD

**Issue by void4** [astropy/astroplan#520]
When calling target_rise_time() with a target that is always up from the observers' location, it sensibly returns no value and logs this warning:

> WARNING: TargetAlwaysUpWarning: Target with index 0 does not cross horizon=0.0 deg within 24 hours [astroplan.observer]

Would it be possible to add a keyword argument to target_rise_time, e.g. throw=True that would throw TargetAlwaysUpWarning as an exception so this case can be caught and handled separately?

I didn't find a separate is_target_always_up() function on the observer class...

**Comment by wtgee** [comment]
You can use a context manager to make a non global suppression:

https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings
