### ISSUE TITLE
Observer.parallactic_angle uses LMST instead of LAST

### ISSUE THREAD

**Issue by JSKenyon** [astropy/astroplan#534]
Whilst comparing various method of computing parallactic angle, I found that `Observer.parallactic_angle` always gives results which differ from e.g. `python-casacore` and `skyfield`. The major source of this discrepancy is that the underlying code makes use of Local Mean Sidereal Time (LMST) instead of Local Apparent Sidereal Time (LAST). Would it be possible to expose both the `kind` and `model` parameters in the interface to `Oberserver.parallactic_angle`?

**Comment by bmorris3** [comment]
Hi @JSKenyon, certainly! There's a link above this comment to a pull request I just made which implements this feature request. I'll try to get tests passing and merge it ASAP. Thanks!

**Comment by bmorris3** [comment]
The new requested feature has been implemented and merged in https://github.com/astropy/astroplan/pull/535! Thanks for this idea, @JSKenyon. 🎉

**Comment by JSKenyon** [comment]
Thanks for your quick response and fix @bmorris3!
