### ISSUE TITLE
Revisit test matrix: remove python 3.7

### ISSUE THREAD

**Issue by wtgee** [astropy/astroplan#555]
You should probably drop Python 3.7. It is picking up a very old `astropy` (4.3.1).

_Originally posted by @pllim in https://github.com/astropy/astroplan/issues/554#issuecomment-1572975888_

EOL for Python 3.7 is 2023-06-27 ([schedule](https://devguide.python.org/versions/)) so we should consider removing support from our test mtarix.

The `tox.ini` file also specifies a number of versions of astropy that are quite old and doesn't specifically support the `5.x` branch, so we should clean that up as well.

**Comment by wtgee** [comment]
I'll try to sit down this weekend and work on some of this and get a PR submitted.

**Comment by pllim** [comment]
FWIW, astropy 5.3 also dropped Python 3.8 to follow numpy, see astropy/astropy#14286 .
