### ISSUE TITLE
Deprecation Warnings in observer.moon_rise_time()

### ISSUE THREAD

**Issue by dalerye** [astropy/astroplan#557]
The Astroplan functions observer.moon_rise_time() and observer.moon_set_time() apparently call the Astroplan function get_moon(), which is now deprecated in favor of get_body("moon"). As a result, every call to the Astroplan functions now generates a deprecation warning in the output. Are there plans to fix this, or is there some other way to easily calculate moon rise and set times in Astroplan?

**Comment by bmorris3** [comment]
Hi @dalerye, there's a fix in https://github.com/astropy/astroplan/pull/558. I'll merge that as soon as the tests pass. Thanks for the heads up!
