### ISSUE TITLE
Plotting style

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#74]
Currently we're using the default matplotlib plotting style:
![](http://astroplan.readthedocs.org/en/latest/tutorials/plots-4.png)

IMO it's not very pretty we should adopt the Astropy plotting style (see [here](http://astropy.readthedocs.org/en/latest/visualization/index.html#module-astropy.visualization.mpl_style), but it doesn't show up because of Astropy Sphinx bugs, sigh) or define our own.
It's pretty easy to implement, se [here](https://github.com/gammapy/gammapy/pull/317/files#diff-85987f48f1258d9ee486e3191495582dR45) and [here](https://github.com/gammapy/gammapy/pull/317/files#diff-dacd6d8705915fd7dcf08a0771d28dddR1) how it was done in Gammapy.

I think there also was talk about a "dark style" for astroplan, but now I can't find any issue for that.

What do you think?

I've put the 0.2 milestone, but if someone wants to implement this today for 0.1, it should be possible.

**Comment by jberlanga** [comment]
We did talk about a "dark style", and I put that in the TODO section of all the plotting function docstrings, but it has since taken a back seat to other matters.

Matplotlib is coming out with new defaults [soon](http://matplotlib.org/style_changes.html).  Maybe we should wait until after?

**Comment by cdeil** [comment]
I haven't seen the new matplotlib style (other than the color map), but I trust it's going to be good, so am OK with us using.
But there's the issue that we want to support both matplotlib 1 and 2, i.e. our image comparison tests should work with either.
Probably the simplest solution is to define our own style (which could be just a copy of the default matplotlib 2.0 style)

I've mentioned this in https://github.com/astrofrog/pytest-mpl/issues/12 ... let's wait and see what @astrofrog recommends.
