### ISSUE TITLE
Improve overview for Astroplan in various places

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#75]
@bmorris3 – Could you please try to improve the overview description for Astroplan in various places before the 0.1 release today?

One place is the "long description" that gets displayed on PyPI, and I think it would be good to have at least a sentence or two and a link e.g. to the docs. Just as an example, see https://pypi.python.org/pypi/gammapy/0.3
The text you see there is from https://github.com/gammapy/gammapy/blob/master/LONG_DESCRIPTION.rst  which gets pulled in like this: https://github.com/gammapy/gammapy/blob/master/setup.py#L40

Really, there's four "landing pages" for new users where we could use the same basic info about Astroplan:
* first part of `README.rst` for someone that goes to the Github repo or has the code locally
* `LONG_DESCRIPTION.rst` for PyPI
* first part of `docs/index.rst` for the docs
* `astroplan/__init__.py` docstring for someone that does `import astroplan` and would like to know how to get started.

I think in all cases one sentence and a link to the online repo and the docs is sufficient, but of course some more info is OK as well.

From Gammapy I know that it's hard to implement this without avoiding some duplication, but I guess that's OK if ingesting the description from another file isn't possible somewhere.
One more thing ... eventually I wanted the top-level docs page to be short and added an About page for Gammapy (https://gammapy.readthedocs.org/en/latest/about.html) ... I think that could be a good idea for Astroplan as well.

PS: I think "Observation planning package for astronomers" is a bit boring  .... "Observing like a boss! –– Astroplan is is the observation planning Kepler and Hubble wished they had." ... @bmorris3 I trust you can come up with some better slogan / short description for astroplan!

**Comment by bmorris3** [comment]
Closed by merge of #79.
