### ISSUE TITLE
FixedTarget mock is active even when remote-data flag is used

### ISSUE THREAD

**Issue by bmorris3** [astropy/astroplan#76]
In #62, we came up with a mock for `FixedTarget.from_name` when the internet is not accessible during tests. That mocked `from_name` method currently gets called during the tests whether or not there is an internet connection, but should only be used when the `--remote-data` flag is not used.

**Comment by eteq** [comment]
I'd suggest this approach: Write two tests, one which is marked with ``@remote_data``, and the other with ``@pytest.mark.skipif('...')``.  Most of the "guts" of the test can be in a private function called by each of those tests, and you can just use the two versions to do the mocking or not.

The one catch here is the ``...`` in `skipif`.  I'm not exactly sure how to ask pytest "is remote_data on or not".  If you look deep into the astropy testing machinery, there's [a line](https://github.com/astropy/astropy/blob/master/astropy/tests/pytest_plugins.py#L134) that does ``if not config.getoption('remote_data')``... but the part I'm not sure about is how to get a `config` object actually in a testing module (the usage in the testing machinery is inside a plugin).  There must be some way to do so, but I don't have time right now to delve through the pytest docs to find out...
