### ISSUE TITLE
Tutorials don't have TOC in sidebar

### ISSUE THREAD

**Issue by eteq** [astropy/astroplan#78]
I noticed something curious about the tutorial docs added in #42 : @jberlanga had to add a table of contents manually, but e.g. the getting started page _already_ indexes the sections of the docuemnt in the sidebar table of contents.  It seems like it should be possible to go one level deeper, though, and have the sections show up also for the tutorials.  Anyone know how to do this? (@adrn or @cdeil might have encountered this?)

http://sphinx-doc.org/config.html#confval-html_sidebars seems like it should be helpful, but that would seem to suggest we _already_ should be seeing a local TOC...

**Comment by cdeil** [comment]
@eteq – I don't understand what you'd like to see.

Currently it looks like this, which is OK, no?

<img width="779" alt="screen shot 2015-08-28 at 22 08 01" src="https://cloud.githubusercontent.com/assets/852409/9555982/666111da-4dd1-11e5-8421-fd16758816dc.png">

Ah ... do you mean you want to see little "+" symbols in the sidebar for sections that can be expanded into subsections?
(Example: http://wcsaxes.readthedocs.org/en/latest/)

**Comment by jberlanga** [comment]
@eteq -- I must not have looked closely enough at the docs during our hangout, because this is what I thought you wanted as well.

**Comment by bmorris3** [comment]
@cdeil It looks to me like this has been fixed. Has it?

**Comment by cdeil** [comment]
Moving this to 0.2 ... it shouldn't block the 0.1 release which is long overdue.

**Comment by cdeil** [comment]
I think it would be nice to have the little "+" signs for TOC entries with sub-points as well ... just like it is in `wcsaxes`:

<img width="239" alt="screen shot 2015-09-01 at 23 51 23" src="https://cloud.githubusercontent.com/assets/852409/9618096/644237b8-5104-11e5-9d54-0fac16e31f22.png">

I don't know what's different in our setup.

And @eteq should comment on what he actually meant before we close this issue.

**Comment by bmorris3** [comment]
@eteq Could you confirm if the TOC now appears as you intended?

**Comment by bmorris3** [comment]
@cdeil With the switch by @bsipocz to the astropy-style RTD theme, [things look quite different today](http://astroplan.readthedocs.io/en/latest/). Should this issue still be open?

**Comment by cdeil** [comment]
I'm not a fan of the astropy-style theme, or the way navigation works now.

Before one could navigate everywhere via the side bar.

Now if you go here the sidebar is empty and you have to navigate via links on the main page:
http://astroplan.readthedocs.io/en/latest/tutorials/index.html

But it's a matter of taste, and I don't have time to discuss or file a PR, so I'm unsubscribing from this issue now.

@eteq - You filed it originally. Close? Or do you still propose some change here?
