### ISSUE TITLE
Split core into several parts

### ISSUE THREAD

**Issue by cdeil** [astropy/astroplan#84]
I propose we split `core.py` (currently ~ 2000 lines) and `test_core.py` (currently ~ 1000 lines) into several smaller files.

**Comment by bsipocz** [comment]
:+1:

**Comment by adrn** [comment]
I can do this once some of the open PRs are merged (for the 0.1 release)

**Comment by bmorris3** [comment]
@adrn Is that just `constraints`?

**Comment by bmorris3** [comment]
@adrn If you were waiting on `constraints` (#61), it's merged.

**Comment by eteq** [comment]
:+1:, although perhaps this should be after 0.1 so that there's some time to shake out any bugs it might introduce?

**Comment by adrn** [comment]
Hm, fair point -- what was that you said? I can put this off a few days? Ok you convinced me! 0.2 it is
