### ISSUE TITLE
tests cannot be run if matplotlib and pytest-mpl are not installed

### ISSUE THREAD

**Issue by eteq** [astropy/astroplan#86]
I've encountered an issue that I think is caused by ``pytest-mpl``, which it looks to me was integrated into astroplan in #13 (@cdeil ?): if I try to run the tests for astroplan on a machine where matplotlib is installed but ``pytest-mpl`` is *not*, I see the following error before the tests even start:
```
% python setup.py test
running test
running build
running build_py
usage: -c [options] [file_or_dir] [file_or_dir] [...]
-c: error: unrecognized arguments: --mpl --mpl-baseline-path=astroplan/plots/tests/baseline_images
```
I think this is due to the line in the pytest section of ``setup.cfg`` which says ``addopts = --mpl --mpl-baseline-path=astroplan/plots/tests/baseline_images``.  Presumably that fails if ``pytest-mpl`` is absent.  Is there a way to still use ``pytest-mpl`` when present but just skip the tests (and not have the command line failure) if it's absent?

cc @astrofrog as I imagine this might show up in other ``pytest-mpl`` situations

**Comment by cdeil** [comment]
@eteq – I noticed the same issue on travis-ci and already asked @astrofrog for help at https://github.com/astropy/astroplan/pull/83#issuecomment-135899418 and https://github.com/astropy/astroplan/pull/83#issuecomment-135904296 .

At the moment `pytest-mpl` is a **required** dependency to be able to run the `astroplan` tests.
I think this is acceptable, but I'd also prefer to have it optional as you describe.
But I don't know how to implement it that way.

@bsipocz – you mentioned that you're implementing image comparison tests for photutils. Have you found a solution for this issue?

**Comment by bsipocz** [comment]
@cdeil - Nope, I stuck at an earlier point with decorating a decorator https://github.com/astropy/photutils/issues/271#issuecomment-135878383.

**Comment by bsipocz** [comment]
btw I don't see any problems with having a requirement of ``pytest-mpl`` for tests, there are extra requirements there already for tests an docs builds.

**Comment by cdeil** [comment]
@bsipocz – Actually, at the moment, it's not just `pytest-mpl` that's a required dependency.
It's also `matplotlib` and `nose` ... if `matplotlib` is not present, pytest errors out like this:
https://travis-ci.org/astropy/astroplan/jobs/77760727#L512

There must be a better way!

**Comment by bsipocz** [comment]
Ohh, that's not good. Isn't there a way to force a preference order on decorators? So the top one will override, as well as being applied to the decorators below?
I guess my problem in https://github.com/astropy/photutils/issues/271#issuecomment-135878383 can be routed back there, too.

**Comment by cdeil** [comment]
Basically everything in pytest can be configured (see [here](https://pytest.org/latest/plugins.html) or [here](https://pytest.org/latest/plugins.html#pytest-hook-reference) [here](https://github.com/astropy/astropy/blob/master/astropy/tests/pytest_plugins.py)), so I'm sure it's possible to set this up.

But I'm hoping @astrofrog will tell us how to set this up, so for now I won't spend time on this, trying to implement a solution ...

**Comment by bsipocz** [comment]
Good idea. I'll do that, too.

**Comment by cdeil** [comment]
Moving this to 0.2 ... it shouldn't block the 0.1 release which is long overdue.

**Comment by eteq** [comment]
@cdeil - I disagree that this is acceptable.  In the current state, users and most devs *cannot* run the test suite, because `pytest-mpl` is pretty niche. That's a big problem for an early release like this because I strongly suspect the tests *will* fail for some people and that will give us useful feedback on how to fix things.  So I would instead advocate either trying to get it to work or just turning this off for the release (it looks to me like adding a ``#`` to the correct line in ``setup.cfg`` does the trick).

**Comment by eteq** [comment]
(I'll spend a little time shortly on trying to get this to actually work using the programmatic configuration, though)

**Comment by cdeil** [comment]
@eteq – Agree to turn this off, because it might be annoying to users or potential new devs.
Thanks for having a look!

**Comment by eteq** [comment]
In #90 I *think* I figured out how to get it to happen programatically.
