### ISSUE TITLE
Feature request: easy access to hour angle, local sidereal time

### ISSUE THREAD

**Issue by bmorris3** [astropy/astroplan#88]
I was observing last night and found myself using TUI to find the hour angle of my target, and the local sidereal time at the observatory. It'd be great if there was: 

* a thin wrapper around the [`time.sidereal_time()` function](http://astropy.readthedocs.org/en/latest/time/#sidereal-time) on `Observer`, i.e. `Observer.local_sidereal_time(time, ['mean' or 'apparent'])`since it requires location information
* a little convenience method for hour angle, which is simply the local sidereal time minus the right ascension of the target

**Comment by wtgee** [comment]
I wrote one into what we are using just yesterday, so second the need for
it. :)

**Comment by bmorris3** [comment]
@wtgee I'll get to this after v0.1 release, expect it in time for 0.2!
