### ISSUE TITLE
Create caveats/FAQ page in docs.

### ISSUE THREAD

**Issue by jberlanga** [astropy/astroplan#89]
Make page like [this](http://docs.astropy.org/en/latest/known_issues.html) for astroplan's known issues, including the issue referred to [here](https://github.com/astropy/astroplan/pull/87#issuecomment-136974723).

**Comment by jberlanga** [comment]
UPDATE:  Instead of making an issues page, continue to use the GitHub issue tracker.

A "gotchas"/caveats/FAQ page would better describe [this issue](https://github.com/astropy/astroplan/pull/87#issuecomment-136974723), and would also be more appropriate for things like the IERS Tables page, currently in the [tutorials](https://astroplan.readthedocs.org/en/latest/tutorials/index.html).

**Comment by jberlanga** [comment]
@astropy/astroplan-maintainers - I've updated this issue and moved it to 0.2 release since I most likely won't get to it in the next few days, but if anyone else wants to move things around, feel free to do so.

**Comment by bmorris3** [comment]
@jberlanga :ear: Did I hear a call for help? I'm on it!
