### ISSUE TITLE
Differences in calculated times between machines.

### ISSUE THREAD

**Issue by jberlanga** [astropy/astroplan#91]
Astroplan sometimes gives different calculated times for the same calculation on different machines:

    >>> sunset_tonight.iso
    Expected:
        '2015-06-16 04:59:11.267'
    Got:
        '2015-06-16 04:59:10.593'

Could be due to differences in local IERS tables/interpolation used to calculate rise/set times, etc? 

See comment [here](https://github.com/astropy/astroplan/pull/87#issuecomment-136974723) for existing discussion, and [here](https://travis-ci.org/astropy/astroplan/jobs/78017167#L673) for original source.

**Comment by bmorris3** [comment]
This is almost certainly related to the [precision limitations discussed on the FAQ page](http://astroplan.readthedocs.org/en/latest/faq/precision.html), not a bug.
