### ISSUE TITLE
Get doctests working as widely as possible

### ISSUE THREAD

**Issue by eteq** [astropy/astroplan#95]
This is a bit nebulous, but it's a reminder to try to put in some effort for 0.2 into getting the doctests to run on the tutorials as much as possible.  As discussed in #87, it's an important way to keep docs and code in sync.

The biggest challenge to this is #91 - for whatever reason some of the rise/set times seem to be either machine or time-dependent, which makes the doctests harder to write.  It might be the best solution is to reprocess these docs to instead print results less sensitive to these things.  E.g., render times in ways that only show to the minute like:

``` python
>>> from astropy.time import Time
>>> now = Time.now()
>>> now.datetime.strftime('%B %d, %Y %H:%M')
'September 03, 2015 16:40'
```

cc @adrn @jberlanga @bmorris3 @cdeil @bsipocz (parties to the discussion in #87)

**Comment by bmorris3** [comment]
I'm apprehensive to use a `now.datetime.strftime`-type pattern in the docs, because it should be clear that you don't have to do that in your own code. If we had to rewrite all of the docs to use that pattern, users might think that's what you're supposed to do.

**Comment by eteq** [comment]
well, arguably that *is* what they're supposed to do if they want a representation like that.  But I see your point that it then wouldn't be clear that ``now.iso`` also gives a fairly nice output (or even just the `__repr__` of ``now``)

**Comment by jberlanga** [comment]
@eteq @bmorris3 Well, we could make a note to the user that they don't have to do format their time output this way.  

Is there a way to locally recreate the environment that the tests are being run on so that the example output is synced with the test output, at least at the time of merging?

**Comment by bmorris3** [comment]
I think we achieved this goal in several PRs over the years, closing!
